@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to accept purchase offers
    activate System

    loop for all the properties

    System --> Agent : shows property and lists its purchase offers
    deactivate System

    Agent -> System  : selects offer to be accepted
    activate System

    System --> Agent : displays operation success
    deactivate System

    end loop


@enduml