@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to accept purchase orders
    activate System

    loop for all properties available for purchase

    System --> Agent : displays properties available for purchase \nand asks to select one to view orders
    deactivate System

    Agent -> System : selects property to view purchase orders.
    activate System

    alt purchaseOrderList != empty
    loop while acceptanceAnswer != yes

    System -->  Agent: displays purchase order and asks the acceptance answer
    deactivate System

    Agent -> System  : selects acceptance answer
    activate System

    System --> Agent : displays operation success
    deactivate System

    end loop
    end alt
    end loop



@enduml