@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shANNOUNCEowing false\

participant ":ImportLegacyInformationController" as CTRL
participant "legacySystemDto\n:legacySystemDto" as DTO
participant "agency\n:Agency" as AGENCY
participant "announcementList\n:AnnouncementList" as LIST
participant "announcement\n:Announcement" as ANNOUNCE
participant "commission\n:Commission" as COMMISSION


    autonumber 23

     -> CTRL : publishAnnouncement(legacySystemDto, agency, agent, ownerEmail)
    activate CTRL

    autonumber 23.1

    group Publish Announcement

    |||
    CTRL -> CTRL : getRequestFromLegacy(legacySystemDto, agency, agent, ownerEmail)
    activate CTRL

    ref over CTRL
        Create Request
    end ref

        CTRL --> CTRL : request
    deactivate CTRL
|||
    CTRL -> DTO : getCommissionValue()
    activate DTO

    DTO --> CTRL : commissionValue
    deactivate DTO


    CTRL -> DTO : getAnnouncementAcceptanceDate()
    activate DTO

        DTO --> CTRL : acceptanceDate
    deactivate DTO

 CTRL -> DTO : getPropertySalePrice()
    activate DTO

        DTO --> CTRL : propertySalePrice
    deactivate DTO

    CTRL -> AGENCY : publishAnnouncementFromLegacy(agent, acceptanceDate, commissionValue, request,propertySalePrice)
    activate AGENCY

        AGENCY -> ANNOUNCE**: create(agent, acceptanceDate, commissionValue, request,propertySalePrice)
        activate ANNOUNCE

        ANNOUNCE -> COMMISSION** : create(commissionValue)
     deactivate ANNOUNCE

    AGENCY -> LIST: addAnnouncement(announcement)
    activate LIST

        LIST -> LIST: validateAnnouncement(announcement)
        activate LIST
            LIST --> LIST
        deactivate LIST

        LIST --> AGENCY : announcement
    deactivate LIST

        AGENCY --> CTRL : announcement
    deactivate  AGENCY

    end group

autonumber 24

    <-- CTRL : operationSucess
    deactivate CTRL

@enduml