@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "request\n:Request" as REQUEST
participant "property\n:Property" as PROPERTY
participant "location\n:Location" as LOCATION


autonumber 37

        -> REQUEST** : createRequest(ownerEmail, propertyType,streetName, city, district, state,\nzipCode, distanceCityCentre, price, photograph,numberBedrooms,\nnumberParkingSpaces,existenceBasement,inhabitableLoft, numberBathrooms,\n availableEquipment, sunExposure)
         activate REQUEST

autonumber 37.1

    group Create Request

        REQUEST -> PROPERTY** : create(propertyType,streetName, city, district, state,\nzipCode, distanceCityCentre, price, photograph,numberBedrooms,\nnumberParkingSpaces,existenceBasement,inhabitableLoft, numberBathrooms,\n availableEquipment, sunExposure)
        activate PROPERTY

        PROPERTY -> LOCATION** : createLocation(streetName, city, district, state, zipCode)

        PROPERTY --> REQUEST : property
        deactivate PROPERTY

        REQUEST -> REQUEST : getCurrentDate()
        activate REQUEST

        REQUEST --> REQUEST :
        deactivate REQUEST
        |||

    end
autonumber 38
        <-- REQUEST : request
        deactivate REQUEST


@enduml