@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false\



participant ":PublishAnnouncementController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agencyRepository\n:AgencyRepository" as AgencyRepository
participant "agency\n:Agency" as AGENCY


autonumber 21

             -> CTRL : getAgentFromSession()
             activate CTRL

autonumber 21.1

    group Get Agent

             CTRL -> _APP: getInstance()
             activate _APP
             _APP -> CTRL: appSession
             deactivate _APP


             CTRL -> APP: getCurrentSession()
             activate APP

                 APP --> CTRL: currentSession
             deactivate APP

             CTRL -> SESSION: getUserEmail()
             activate SESSION

                 SESSION --> CTRL: email
             deactivate SESSION


             CTRL -> PLAT: getAgencyRepository()
             activate PLAT

                 PLAT --> CTRL: agencyRepository
             deactivate PLAT


             CTRL -> AgencyRepository: getAgencyByUserEmail(email)
             activate AgencyRepository

                 loop [for each agency
                     AgencyRepository -> AGENCY : anyAgentHasEmail(email)
                     activate AGENCY

                          AGENCY --> AgencyRepository : true/false
                     deactivate AGENCY
                 end
                 AgencyRepository --> CTRL : agency
             deactivate AgencyRepository

             CTRL -> AGENCY: getAgentByEmail(email)
             activate AGENCY

                 AGENCY --> CTRL : agent
             deactivate AGENCY




    end

autonumber 22

    <-- CTRL : agent

@enduml