@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Agent" as ADM
participant ":PublishAnnouncementUI" as UI
participant ":PublishAnnouncementController" as CTRL
participant "agency\n:Agency" as AGENCY
participant "announcement\n:Announcement" as AD
participant "request\n:Request" as REQUEST

activate ADM

            ADM -> UI : asks to publish an announcement
            activate UI

                UI -> CTRL** : create

                UI -> CTRL : getCommissionTypeList()

                    ref over CTRL
                                Get Commission Type List
                    end ref

                    activate CTRL

                    CTRL --> UI : commissionTypeList
                deactivate CTRL

                UI --> ADM : shows type of commission list\n and asks to select one

            deactivate UI

            ADM -> UI : selects a type of commission
            activate UI


            UI --> ADM : requests value of commission
            deactivate UI

            ADM -> UI : enters commission value
            activate UI


            UI --> ADM : requests owner email
            deactivate UI

            ADM -> UI : enters requested data (ownerEmail)
            activate UI


            UI -> CTRL : getTypePropertyList()

            ref over CTRL
                        Get Property Type List
            end ref

            activate CTRL

            CTRL --> UI : PropertyTypeList
            deactivate CTRL


        UI --> ADM : shows types of properties and asks to select one
        deactivate UI

        ADM -> UI : selects a type of property
        activate UI



        UI -> CTRL : getPropertyTypeByDescription(commissionTypeDescription)
        activate CTRL
            ref over CTRL
            Get Property Type
            end ref
        CTRL -->  UI: propertyType
        deactivate CTRL

        UI --> ADM : requests location of the property
        deactivate UI

        ADM -> UI : types requested data (streetName, city, district, state, zipCode)
        activate UI


        UI --> ADM :  requests area of the property
        deactivate UI

        ADM -> UI : types requested data (area)
        activate UI


        UI --> ADM :  requests distance from city center of the property
        deactivate UI

        ADM -> UI : types requested data (distanceCityCentre)
        activate UI

        UI --> ADM :  requests price of the property
        deactivate UI

        ADM -> UI : types requested data (price)
        activate UI


 alt type of property = residence

        autonumber 30.1
        UI --> ADM : requests data (number of bedrooms, number of parking spaces)
        deactivate UI

        ADM -> UI : types requested data
        activate UI

            UI --> ADM : requests URI photograph of property
            deactivate UI


                loop  min=1 max=30

                    ADM -> UI : types requested data (uri)
                    activate UI

                    UI -> CTRL : addPhotographUri(uri)
                    activate CTRL

                    ref over CTRL
                        Add Photograph Uri
                    end ref

                     CTRL --> UI : photograph
                    deactivate CTRL
                end loop


        UI --> ADM : requests number of bathrooms
        deactivate UI

                opt numberBathrooms
                ADM -> UI : types requested data (numberBathrooms)
                activate UI
                end opt

        UI --> ADM : requests available equipment
        deactivate UI

                opt availableEquipment
                        loop availableEquipment
                            ADM -> UI : types requested data (availableEquipment)
                            activate UI

                            UI -> CTRL : addAvailableEquipment(description)
                            activate CTRL

                                ref over CTRL
                                Add Available Equipment Description
                                end

                            CTRL --> UI : availableEquipment
                            deactivate CTRL
                        end loop
                 end opt

else type of property = house

        autonumber 30.1
        UI --> ADM : requests data (existence of basement; inhabitable loft)
        deactivate UI

        ADM -> UI : types requested data
        activate UI

            UI --> ADM : asks to select sun exposure
            deactivate UI

            opt sun exposure
            ADM -> UI : selects requested data (sunExposure)
            activate UI
            end opt

    end
    autonumber 31
    UI --> ADM : shows all data and asks for confirmation
        deactivate UI

    ADM -> UI : submits data
    activate UI

        UI -> CTRL : publishAnnouncement(commissionValue, commissionTypeDescription, ownerEmail, propertyTypeDescription,\nstreetName, city, district, state, zipCode, area, distanceCityCentre,\nprice, photograph, numberBathrooms, availableEquipment, sunExposure)
        activate CTRL

        CTRL -> CTRL : getAgentFromSession()

            ref over CTRL
                Get Agent
            end ref

            activate CTRL

        CTRL --> CTRL : agent
        deactivate CTRL

        |||
        CTRL -> AD : createRequest(ownerEmail, propertyType, streetName, city, district,\n state, zipCode, area, distanceCityCentre,price, photograph,\n numberBathrooms, availableEquipment, sunExposure)
        activate AD

        AD -> REQUEST** : create(ownerEmail, propertyType,streetName, city, district, state,\n zipCode, distanceCityCentre, price, photograph,\n numberBathrooms, availableEquipment, sunExposure)
        activate REQUEST
            |||
            ref over REQUEST
                Create Request
            end ref

        REQUEST --> AD : request
        deactivate REQUEST

        AD -> AD : addRequest(request)
        activate AD
        AD -> AD : validateRequest(request)
        activate AD

        AD --> AD :
        deactivate AD

        AD --> AD :
        deactivate AD

        AD -->CTRL : request

        deactivate AD

        CTRL -> CTRL : getCommissionTypeByDescription(commissionTypeDescription)
        activate CTRL
            ref over CTRL
            Get Commission Type
            end ref
        CTRL --> CTRL : commissionType
        deactivate CTRL

            CTRL -> AGENCY: publishAnnouncement(agent, commission, request)

                ref over AGENCY
                    Publish Announcement
                end ref

                activate AGENCY

            AGENCY --> CTRL: announcement
            deactivate AGENCY

            CTRL --> UI: announcement
            deactivate CTRL

            UI --> ADM: displays operation success
            deactivate UI

deactivate ADM

@enduml