@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "commissionTypeRepository:\nCommissionTypeRepository" as CommissionTypeRepository

autonumber 40
-> CTRL : getCommissionTypeByDesignation(designation)

autonumber 40.1

activate CTRL
    group Get Commission Type
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getCommissionTypeRepository()
        activate PLAT

            PLAT -> CTRL : commissionTypeRepository
        deactivate PLAT

        CTRL -> CommissionTypeRepository : getCommissionTypeByDesignation(designation)
        activate CommissionTypeRepository

            CommissionTypeRepository --> CTRL : commissionType
        deactivate CommissionTypeRepository

    end group

    autonumber 41
    <-- CTRL : commissionType

deactivate CTRL


@enduml