@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false\


participant "agency\n:Agency" as AGENCY
participant "announcementList\n:AnnouncementList" as ADList
participant "smsNotification\n:SmsNotification" as SMSNOT
participant "announcement\n:Announcement" as AD
participant "commission\n:Commission" as COMMISSION

autonumber 23

             -> AGENCY : publishAnnouncement(agent,commissionType, commissionValue, request)
             activate AGENCY

autonumber 23.1

    group Publish announcement


                AGENCY -> AD**: create(agent, commissionType, commissionValue, request)
                activate AD

                AD -> COMMISSION** : create(commissionValue,commissionType)

                AD --> AGENCY : announcement
                deactivate AD

                AGENCY -> ADList: addAnnouncement(announcement)
                activate ADList

                ADList -> ADList: validateAnnouncement(announcement)
                activate ADList

                ADList --> ADList
                deactivate ADList

                opt  announcement is valid
                ADList -> SMSNOT : sendNotification(agentPhoneNumber, \npropertyLocation,acceptanceDate)
                activate SMSNOT

                SMSNOT --> ADList : success
                deactivate SMSNOT
                end opt

                ADList --> AGENCY : success
                deactivate  ADList
    end

autonumber 24

    <-- AGENCY : announcement
    deactivate AGENCY

@enduml