@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "agency\n:Agency" as AGENCY
participant "requestList\n:RequestList" as REPLIST
participant "announcementMapper\n:AnnouncementMapper" as MAPPER
participant "announcementDto\n:AnnouncementDto" as DTO
participant "request\n:Request" as REQUEST



autonumber 46

        -> AGENCY: createSaleRequest(announcementDto, propertyType,agent)
         activate AGENCY

autonumber 46.1

    group Create Request

        AGENCY -> MAPPER: toModelRequest(announcementDto,propertyType,agent)
        activate MAPPER

       MAPPER -> DTO : ownerEmail = getOwnerEmail()
      activate DTO
      deactivate DTO

        MAPPER -> DTO : amount = getAmount()
        activate DTO
        deactivate DTO

        MAPPER -> DTO : area = getArea()
        activate DTO
        deactivate DTO

        MAPPER -> DTO : streetName = getStreetName()
        activate DTO
        deactivate DTO

        MAPPER -> DTO : city = getCity()
        activate DTO
        deactivate DTO

        MAPPER -> DTO : district = getDistrict()
        activate DTO
        deactivate DTO

        MAPPER -> DTO : state = getState()
        activate DTO
        deactivate DTO

        MAPPER -> DTO : zipcode = getZipcode()
        activate DTO
        deactivate DTO

        MAPPER -> DTO : distanceCityCenter = getDistanceCityCenter()
        activate DTO
        deactivate DTO

        MAPPER -> DTO: uriList = getUriList()
        activate DTO
        deactivate DTO
        alt propertyType == land

        MAPPER -> MAPPER : createPropertySaleRequest(propertyType, amount,\n area, streetName, city, district,\nstate, zipCode, distanceCityCenter,uriList,agent)
        activate MAPPER
  |||
           ref over MAPPER

                Create Property Sale Request

           end ref
        MAPPER --> MAPPER:
        deactivate MAPPER

        |||
        else propertyTypeDesignation = house || propertyTypeDesignation = apartment

            MAPPER -> DTO : numberBedrooms = getNumberBedrooms()
            activate DTO
            deactivate DTO

            MAPPER -> DTO : numberBathrooms = getNumberBathrooms()
            activate DTO
            deactivate DTO

            MAPPER -> DTO : numberParkingSpace = getParkingSpace()
            activate DTO
            deactivate DTO

            MAPPER -> DTO : availableEquipmentDescriptionList= getAvailableEquipmentList()
            activate DTO
            deactivate DTO


            opt propertyTypeDesignation = Apartment
            MAPPER -> MAPPER: createResidenceSaleRequest(propertyType, amount,\n area, streetName, city, district,\nstate, zipCode, distanceCityCenter,uriList,agent,\nnumberBedrooms,numberBathrooms,\nnumberParkingSpace,availableEquipmentDescriptionList)
            activate MAPPER

                  |||
                  ref over MAPPER

                       Create Residence Sale Request

                  end ref


            MAPPER --> MAPPER : request
            deactivate MAPPER
            |||
        end opt

        opt propertyType = house

            MAPPER -> DTO : existenceBasement = getBasement()
            activate DTO
            deactivate DTO

            MAPPER -> DTO : inhabitableLoft = getInhabitableLoft()
            activate DTO
            deactivate DTO

            MAPPER -> DTO : sunExposure = getSunExposure()
            activate DTO
            deactivate DTO

            MAPPER -> MAPPER : createHouseSaleRequest(propertyType, amount,\n area, streetName, city, district,\nstate, zipCode, distanceCityCenter,uriList,agent,\nnumberBedrooms,numberBathrooms,\nnumberParkingSpace,availableEquipment,\nexistenceBasement,inhabitableLoft,sunExposure)
            activate MAPPER
              |||
              ref over MAPPER

                   Create House Sale Request

              end ref

            MAPPER --> MAPPER : request
            deactivate MAPPER


             |||
             end opt

            |||
             end alt
            MAPPER --> AGENCY: request
            deactivate MAPPER
            |||
            AGENCY -> AGENCY: addRequest(request)
            activate AGENCY

            AGENCY -> REPLIST : addRequest(request)
            activate REPLIST

                REPLIST -> REPLIST: validateRequest(request)
                activate REPLIST
                REPLIST --> REPLIST
                deactivate REPLIST

            REPLIST --> AGENCY
            deactivate REPLIST

            AGENCY --> AGENCY
            deactivate AGENCY
    |||
    end

autonumber 47
        <-- AGENCY: request
        deactivate AGENCY


@enduml