@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "agency\n:Agency" as AGENCY

autonumber 8
-> ORG: RegisterAgency(ID, designation, streetName, city,\n district, state, zipCode, phoneNumber, email)

autonumber 9
activate ORG
    group Register Agency

        ORG -> AGENCY: register(ID, designation, streetName, city,\n district, state, zipCode, phoneNumber, email)
        ORG -> ORG: addAgency (Agency)

        activate ORG
            ORG -> ORG: validateAgency(Agency)
            activate ORG
                ORG --> ORG
            deactivate ORG

            ORG --> ORG
        deactivate ORG
    end

    autonumber 14
    <-- ORG : agency
deactivate ORG


@enduml