@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US001

autonumber

actor "Unregistered user" as User
participant ":System" as System

activate User

    User -> System : asks to display listed properties
    activate System

    System --> User : display listed properties by most recent added
    deactivate System

    opt type of business
        User -> System : asks to select type of business
        activate System

        System --> User : shows types of business and request data
        deactivate System

        User -> System : selects data (businessType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen
        deactivate System
    end

    opt type of property
        User -> System : asks to select type of property
        activate System

        System --> User : shows types of properties and request data
        deactivate System

        User -> System : selects data (propertyType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen
        deactivate System
    end

    alt properType != land

        opt number of bedrooms
            User -> System : asks to select number of bedrooms
            activate System

            System --> User : shows options for number of bedrooms and request data
            deactivate System

            User -> System : selects data (numberBedrooms)
            activate System

            System --> User : display all the listed properties, according to the \ncriteria chosen
            deactivate System
        end

    end

    opt price
        User -> System : asks to sort announcements by price
        activate System

        System --> User : shows options for sort announcements by price and request data
        deactivate System

        User -> System : select data (sortingType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen
        deactivate System
    end

    opt city
        User -> System : asks to sort announcements by city
        activate System

        System --> User : shows options for sort announcements by city and request data
        deactivate System

        User -> System : select data (sortingType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen
        deactivate System
    end

    opt state
        User -> System : asks to sort announcements by state
        activate System

        System --> User :  shows options for sort announcements by state and request data
        deactivate System

        User -> System : select data (sortingType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen
        deactivate System
    end


@enduml