@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US001

autonumber

actor "Unregistered user" as User
participant ":System" as System

activate User

    User -> System : asks to display listed properties
    activate System

    System --> User : display listed properties by most recent added

    opt type of business
        System --> User : shows type of business and asks to select one
        deactivate System

        User -> System : selects data (BusinessType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen

    end

    opt type of property
        System --> User : shows types of properties and asks to select one
        deactivate System

        User -> System : selects data (propertyType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen

    end

    alt properType != land

        opt number of bedrooms
            System --> User : shows options for number of bedrooms and asks to select one
            deactivate System

            User -> System : selects data (numberBedrooms)
            activate System

            System --> User : display all the listed properties, according to the \ncriteria chosen

        end

    end

    opt price
        System --> User : shows options for sort properties by price and asks to select one
        deactivate System

        User -> System : select data (sortingType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen

    end

    opt city
        System --> User : shows options for sort properties by city and asks to select one
        deactivate System

        User -> System : select data (sortingType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen

    end

    opt state
        System --> User :  shows options for sort properties by state and asks to select one
        deactivate System

        User -> System : select data (sortingType)
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen
        deactivate System
    end


@enduml