@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US001

autonumber

actor "Unregistered user" as User
participant ":System" as System

activate User

    User -> System : asks to display listed properties
    activate System

    System --> User : display listed properties by most recent added \nand asks to select data (type of business)
    deactivate System

    opt type of business
        User -> System : selects data (type of business)
        activate System
    end

    System --> User : asks to select data (type of property)
        deactivate System

    opt type of property
        User -> System : selects data (type of property)
        activate System
    end

    System --> User : asks to select data (number of bedrooms)
        deactivate System

    opt number of bedrooms
        User -> System : selects data (number of bedrooms)
        activate System
    end

    System --> User : display all the listed properties, according to the \ncriteria chosen and asks to select data (price)
        deactivate System

    opt price
       User -> System : selects data (price)
       activate System

       System --> User :  asks to select data (type of sorting)
       deactivate System

       User -> System : select data (type of sorting)
       activate System
    end

    System --> User : asks to select data (city)
        deactivate System

    opt city
       User -> System : selects data (city)
       activate System

       System --> User :  asks to select data (type of sorting)
       deactivate System

       User -> System : select data (type of sorting)
       activate System
    end

    System --> User : asks to select data (state)
        deactivate System

    opt state
       User -> System : selects data (state)
       activate System

       System --> User :  asks to select data (type of sorting)
       deactivate System

       User -> System : select data (type of sorting)
       activate System
    end

    System --> User : display all the listed properties, according to the \ncriteria chosen
        deactivate System


@enduml