@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing true

title System Sequence Diagram (SSD) - US004

autonumber

actor "<b>Owner</b>" as Owner
participant "<b>:System</b>" as System

activate Owner

    Owner -> System : asks to create a new request
    activate System

        System --> Owner : requests data
    deactivate System

    Owner -> System : types requested data (property's name, reference, description, location,\n distance from City Center, area)
    activate System

        System --> Owner : shows property's lists and asks to select one
    deactivate System


    System --> "Owner" : requests data
    activate System
    Owner -> System : imports requested data (photographs/pictures)

        deactivate System

    Owner -> System : selects a property's list
'    activate System
'    deactivate System

    alt Rental
        autonumber 8
        System --> "Owner": requests data
        activate System

        "Owner" -> System: types requested data (rent, contract's duration)
        deactivate System

    else Sale
        autonumber 8
         System --> "Owner": requests data
        activate System

        "Owner" -> System: types requested data (price)
        deactivate System

    end

    System --> "Owner" : shows property's types and asks to select one
    activate System
    Owner -> System : selects property's type
    deactivate System

   alt Apartment

        System --> "Owner": requests data
        activate System

        "Owner" -> System: types requested data (bedrooms, bathrooms)
        deactivate System

    System --> "Owner": requests data
                    activate System

                    "Owner" -> System: selects requested data (central heating, air conditioning)
                    deactivate System

    else House
        autonumber 12
         System --> "Owner": requests data
        activate System

        "Owner" -> System: types requested data (bedrooms, bathrooms)
        deactivate System

         System --> "Owner": requests data
                activate System

                "Owner" -> System: selects requested data (central heating, air conditioning, basement,\n inhabitable loft, sun exposure)
                deactivate System

    else Land

    ...No extra steps when selecting this option...

    end

        System --> Owner : requests the selection of an agent
    activate System

    "Owner" -> System : selects an agent
    deactivate System


        "Owner" -> System : summits the request
    activate System

    System --> "Owner" : displays operation success
    deactivate System

@enduml