@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US008 (Alternative one)

autonumber

actor "Agent" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to display the requests made to himself
    activate System

    System --> Employee : shows the list of requests
    deactivate System

    loop for the requests of the agent

        Employee -> System : asks to make a decision for the request
        activate System

        System --> Employee : shows the request and asks data (option)
        deactivate System

        Employee -> System : submits data (option)
        activate System

        alt option == accept

        System --> Employee : shows types of commission and asks to select one
        deactivate System

        Employee -> System : selects type of commission
        activate System

        System --> Employee : requests value of commission
        deactivate System

        Employee -> System : enters commission value
        activate System

        System --> Employee : shows all data and asks to submits
        deactivate System

        Employee -> System : submits data
        activate System

        else option == decline

        System --> Employee : asks for justification message
        deactivate System

        Employee -> System :submits message
        activate System

        end

        System --> Employee : shows operation success and shows the list of requests
        deactivate System


'        alt accept request
'        Employee -> System : asks to make a request become an announcement
'        activate System
'
'        System --> Employee : shows the request and asks for confirmation
'        deactivate System
'
'        Employee -> System : submits data
'        activate System
'
'        System --> Employee : shows operation success and shows the list of requests
'        deactivate System
'
'        else decline request
'        Employee -> System : asks to decline an announcement request
'        activate System
'
'        System --> Employee : shows the request and asks for justification message
'        deactivate System
'
'        Employee -> System :submits message
'        activate System
'
'        System --> Employee : asks for confirmation
'        deactivate System
'
'        Employee -> System : submits data
'        activate System
'
'        System --> Employee : shows operation success and shows the list of requests
'        deactivate System
'
'        end

'        opt request
'
'        Employee -> System : asks to make a request become an announcement
'        activate System
'
'        System --> Employee : shows the request and asks for confirmation
'        deactivate System
'
'        Employee -> System : submits data
'        activate System
'
'        System --> Employee : shows operation success and shows the list of requests
'        deactivate System
'
'        end

    end

@enduml