@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ScheduleVisitController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "criteriaRepository\n:CriteriaRepository" as CriteriaRepository
participant ":CriteriaMapper" as MAPPER
participant "criteriaDtoList\n:List<CriteriaDto>" as DTOLIST
participant "criteriaDto\n:CriteriaDto" as DTO


autonumber 11

-> CTRL : getCriteriaList()

activate CTRL
autonumber 11.1

    group Get Criteria DTO List

CTRL -> RepositorySingleton : getInstance()

        activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getCriteriaRepository()

        activate PLAT

            PLAT --> CTRL : CriteriaRepository

        deactivate PLAT

        CTRL -> CriteriaRepository : getCriteriaList

        activate CriteriaRepository

        CriteriaRepository --> CTRL : criteriaList

        deactivate CriteriaRepository

        CTRL -> MAPPER : toDto(criteriaList)
        activate MAPPER

        MAPPER -> DTOLIST** : create()

        loop for each criterion

         MAPPER -> MAPPER : criteriaDto = toDto(criterion)
        activate MAPPER

        MAPPER --> DTO** : create(criterion)
        deactivate MAPPER

         MAPPER -> DTOLIST : add(criteriaDto)
        activate DTOLIST
        deactivate DTOLIST

        end loop

        MAPPER --> CTRL : criteriaDtoList

        deactivate MAPPER

     end
     autonumber 12

        <-- CTRL : criteriaDtoList

        deactivate CTRL
@enduml