@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (SD) - US009

autonumber

actor "<b> Customer </b>" as CTM
participant "<b> :ScheduleVisitUI </b>" as UI
participant "<b> :ScheduleVisitController </b>" as CTRL
participant "<b> announcementList</b>\n<b> :AnnouncementList </b>" as LISTCLASS

activate CTM

    CTM -> UI : asks to schedule a new visit
        activate UI

    UI -> CTRL** : create

    UI -> CTRL : getAllNonDealAnnouncementsDto()
        activate CTRL

    CTRL -> CTRL : getAllNonDealAnnouncements()
    activate CTRL
            ref over CTRL
                Get Non Deals List
            end ref
        CTRL --> CTRL : nonDealsList
    deactivate CTRL
|||
    CTRL -> CTRL : toDto(nonDealsList)
    activate CTRL
            ref over CTRL
                Convert List to DTO
            end ref
        CTRL --> CTRL : nonDealsListDto
    deactivate CTRL

        CTRL --> UI : nonDealsListDto
    deactivate CTRL

        UI --> CTM : shows non deals list and asks if the user wants\n to filter the list
    deactivate UI

    loop While the user intends

    CTM -> UI : selects to see criteria to filter the list
    activate UI

    UI -> CTRL : getCriteriaList()
    activate CTRL

    ref over CTRL
        Get Criteria DTO List
    end ref

    CTRL --> UI : criteriaDtoList
    deactivate CTRL

    UI --> CTM : shows criteria list and asks to select a criteria type

    deactivate UI

            CTM -> UI : selects criteria option
            activate UI

            alt option == 1

                UI -> CTRL : getBusinessTypeList()
                activate CTRL

                ref over CTRL
                Get Business Type DTO List
                end ref

                CTRL --> UI : businessTypeDtoList
                deactivate CTRL

                UI --> CTM : shows business type list and asks to select one
                deactivate UI

                CTM -> UI : selects a business type
                activate UI

                UI -> CTRL : getAnnouncementsByBusinessType(businessTypeDto, nonDealsList)
                activate CTRL

                CTRL -> CTRL : getDesignationFromDto(businessTypeDto)
                activate CTRL

                ref over CTRL
                Get Designation from Criteria DTO
                end ref
                CTRL --> CTRL : designation
                deactivate CTRL
|||
                CTRL -> LISTCLASS : announcementHasBusinessType(nonDealsList, businessTypeDesignation)
                activate LISTCLASS

                LISTCLASS --> CTRL : sortedList
|||
                deactivate LISTCLASS

                CTRL -> CTRL : toDto(sortedList)
                    activate CTRL
                            ref over CTRL
                                Convert List to DTO
                            end ref
                        CTRL --> CTRL : sortedListDto
                    deactivate CTRL

                        CTRL --> UI : sortedListDto
                    deactivate CTRL

                        UI --> CTM : shows sorted list and asks if it wants to select more criteria
                    deactivate UI
|||
            else option == 2
            
                CTM -> UI : selects criteria
                activate UI

                UI -> CTRL : getPropertyTypeList()
                activate CTRL

                ref over CTRL
                Get Property Type DTO List
                end ref

                CTRL --> UI : propertyTypeDtoList
                deactivate CTRL

                UI --> CTM : shows property type list and asks to select one
                deactivate UI

                CTM -> UI : selects a property type
                activate UI

                UI -> CTRL : getAnnouncementsByPropertyType(propertyTypeDto, nonDealsList)
                activate CTRL

                CTRL -> CTRL : getDesignationFromDtol(propertyTypeDto)
                activate CTRL

                ref over CTRL
                Get Designation from Criteria DTO
                end ref
                CTRL --> CTRL : designation
                deactivate CTRL
|||
                CTRL -> LISTCLASS : announcementHasPropertyType(nonDealsList, propertyTypeDesignation)
                activate LISTCLASS

                    LISTCLASS --> CTRL : sortedList
|||
                deactivate LISTCLASS
                
                CTRL -> CTRL : toDto(sortedList)
                    activate CTRL
                            ref over CTRL
                                Convert List to DTO
                            end ref
                        CTRL --> CTRL : sortedListDto
                    deactivate CTRL

                        CTRL --> UI : sortedListDto
                    deactivate CTRL

                        UI --> CTM : shows sorted list and asks if it wants to select more criteria
                    deactivate UI
|||
            else option == 3 && propertyType != "Land"

                CTM -> UI : selects criteria
                activate UI

                UI --> CTM : requests data (numberBedrooms)
                deactivate UI

                CTM -> UI : types number of bedrooms
                activate UI

                UI -> CTRL : getAnnouncementsByNumberBedrooms(numberBedrooms, nonDealsList)
                activate CTRL

                CTRL -> LISTCLASS : announcementHasNumberBedrooms(nonDealsList, numberBedrooms)
                activate LISTCLASS

                    LISTCLASS --> CTRL : sortedList
|||
                deactivate LISTCLASS

                CTRL -> CTRL : toDto(sortedList)
                    activate CTRL
                            ref over CTRL
                                Convert List to DTO
                            end ref
                        CTRL --> CTRL : sortedListDto
                    deactivate CTRL

                        CTRL --> UI : sortedListDto
                    deactivate CTRL

                        UI --> CTM : shows sorted list and asks if it wants to select more criteria
                    deactivate UI
                deactivate CTRL
|||
            else option == 4

                CTM -> UI : selects criteria
                activate UI

                UI --> CTM : shows price sorting orders available and asks to select one
                deactivate UI


                CTM -> UI : selects a sorting order
                activate UI

                UI -> CTRL : getAnnouncementsByPrice(sortingOrder, nonDealsList)
                activate CTRL

                alt sortingOrder == "Ascending"
                CTRL -> LISTCLASS : sortAnnouncementsByAscendingPrice(nonDealsList)
                activate LISTCLASS

                    LISTCLASS --> CTRL : sortedList
                deactivate LISTCLASS

                else sortingOrder == "Descending"
                CTRL -> LISTCLASS : sortAnnouncementsByDescendingPrice(nonDealsList)
                activate LISTCLASS

                LISTCLASS --> CTRL : sortedList
                deactivate LISTCLASS

                end alt
|||
               CTRL -> CTRL : toDto(sortedList)
                    activate CTRL
                            ref over CTRL
                                Convert List to DTO
                            end ref
                        CTRL --> CTRL : sortedListDto
                    deactivate CTRL

                        CTRL --> UI : sortedListDto
                    deactivate CTRL

                        UI --> CTM : shows sorted list and asks if it wants to select more criteria
                    deactivate UI
|||
            else option == 5

                CTM -> UI : selects criteria
                activate UI
            
                UI --> CTM : shows city sorting orders available and asks to select one
                deactivate UI


                CTM -> UI : selects a sorting order
                activate UI

                UI -> CTRL : getAnnouncementsByCity(sortingOrder, nonDealsList)
                activate CTRL

                alt sortingOrder == "Ascending"
                CTRL -> LISTCLASS : sortAnnouncementsByAscendingCity(nonDealsList)
                activate LISTCLASS

                LISTCLASS --> CTRL : sortedList
                deactivate LISTCLASS

                else sortingOrder == "Descending"

                CTRL -> LISTCLASS : sortAnnouncementsByDescendingCity(nonDealsList)
                activate LISTCLASS

                LISTCLASS --> CTRL : sortedList
                deactivate LISTCLASS

                end alt
|||
                CTRL -> CTRL : toDto(sortedList)
                activate CTRL
                        ref over CTRL
                            Convert List to DTO
                        end ref
                    CTRL --> CTRL : sortedListDto
                deactivate CTRL

                    CTRL --> UI : sortedListDto
                deactivate CTRL

                    UI --> CTM : shows sorted list and asks if it wants to select more criteria
                deactivate UI
|||
            else option == 6

                CTM -> UI : selects criteria
                activate UI

                UI --> CTM : shows state sorting orders available and asks to select one
                deactivate UI


                CTM -> UI : selects a sorting order
                activate UI

                UI -> CTRL : getAnnouncementsByState(sortingOrder, nonDealsList)
                activate CTRL

                alt sortingOrder == "Ascending"
                CTRL -> LISTCLASS : sortAnnouncementsByAscendingState(nonDealsList)
                activate LISTCLASS

                LISTCLASS --> CTRL : sortedList
                deactivate LISTCLASS

                else sortingOrder == "Descending"

                CTRL -> LISTCLASS : sortAnnouncementsByDescendingState(nonDealsList)
                activate LISTCLASS

                LISTCLASS --> CTRL : sortedList
                deactivate LISTCLASS

                end alt
|||
                deactivate LISTCLASS

                    CTRL -> CTRL : toDto(sortedList)
                    activate CTRL
                            ref over CTRL
                                Convert List to DTO
                            end ref
                        CTRL --> CTRL : sortedListDto
                    deactivate CTRL

                        CTRL --> UI : sortedListDto
                    deactivate CTRL

                        UI --> CTM : shows sorted list
                    deactivate UI
|||
            deactivate CTRL

            deactivate UI

            end alt

        end loop

    CTM -> UI : selects an announcement
        activate UI

    UI -> CTRL : toModel(announcementDto)
    activate CTRL
        ref over CTRL
            Convert Announcement DTO
             to Model
        end ref

        CTRL --> UI : announcement
    deactivate CTRL

    UI --> CTM : requests data (visitDay, visitMonth, visitYear, startHour,\n endHour)
        deactivate UI

    loop While the user intends
    CTM -> UI : types requested data
        activate UI

    UI --> CTM : shows all data and asks to submit
    deactivate UI

    CTM -> UI : submits data
    activate UI

        UI -> CTRL : scheduleVisit(announcement, visitDay, visitMonth, visitYear, startHour, endHour)

        activate CTRL

        ref over CTRL
            Schedule Visit
        end ref
|||
    end loop

    CTRL --> UI : confirmation
    deactivate CTRL

    UI --> CTM : displays operation success
        deactivate UI

@enduml