@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ScheduleVisitController" as CTRL
participant "announcement\n:Announcement" as ANNOUNCE
participant "visit:Visit" as VST
participant "employee\n:Employee" as EMP
participant "person:\nPerson" as PERSON
participant "<interface>\n:Notification" as NOTIFICATION


autonumber 67

    -> CTRL : scheduleVisit(announcement, visitDay,\n visitMonth, visitYear, startHour, endHour)
    activate CTRL

    autonumber 67.1

    group Schedule Visit
   |||
           CTRL -> CTRL : getUserPerson()
           activate CTRL
               ref over CTRL
                   Get User Person
               end ref
               CTRL --> CTRL : person
           deactivate CTRL
|||
    CTRL -> PERSON : userName = getName()
    activate PERSON

        PERSON --> CTRL : userName
    deactivate PERSON


    CTRL -> PERSON : userPhoneNumber = getPhoneNumber()
    activate PERSON

        PERSON --> CTRL : userPhoneNumber
    deactivate PERSON
|||
    CTRL -> ANNOUNCE : createVisit(visitDay, visitMonth, visitYear,\n startHour, endHour, userName, userPhoneNumber)
    activate ANNOUNCE

    ANNOUNCE -> VST** : create(visitDay, visitMonth, visitYear,\n startHour, endHour, userName, userPhoneNumber)

     ANNOUNCE -> ANNOUNCE : addVisit(visit)
     activate ANNOUNCE

     ANNOUNCE -> ANNOUNCE : validateVisit(visit)
     activate ANNOUNCE

        ANNOUNCE --> ANNOUNCE
     deactivate ANNOUNCE

     ANNOUNCE --> ANNOUNCE
     deactivate ANNOUNCE

        ANNOUNCE --> CTRL : visit
    deactivate ANNOUNCE
|||
    CTRL -> ANNOUNCE: agentEmail = getAgentEmail()
    activate ANNOUNCE

    ANNOUNCE -> EMP : getAgentEmail()
    activate EMP

    EMP -> PERSON : getEmailAddress()
    activate PERSON

       PERSON --> EMP : agentEmail
    deactivate PERSON

       EMP --> ANNOUNCE : agentEmail
    deactivate EMP

       ANNOUNCE --> CTRL : agentEmail
    deactivate ANNOUNCE
|||
    CTRL -> NOTIFICATION : sendNotificationMessage(agentEmail)
    activate NOTIFICATION

        NOTIFICATION --> CTRL : confirmation
    deactivate NOTIFICATION
|||
    end group

    autonumber 68
        <-- CTRL : visit
    deactivate CTRL

@enduml