@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ScheduleVisitController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "businessTypeRepository\n:BusinessTypeRepository" as BusinessTypeRepository


autonumber 17

 -> CTRL : getBusinessTypeList()

activate CTRL

    autonumber 17.1

        group Get Business Type Object

        CTRL -> RepositorySingleton : getInstances()
        activate RepositorySingleton

        RepositorySingleton --> CTRL : repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getBusinessTypeRepository()

        activate PLAT

        PLAT --> CTRL : businessTypeRepository
        deactivate PLAT

        CTRL -> BusinessTypeRepository : getBusinessTypeList()

        activate BusinessTypeRepository

        BusinessTypeRepository --> CTRL : businessTypeList
        deactivate BusinessTypeRepository

        end group

autonumber 18
<-- CTRL : businessTypeList
deactivate CTRL

@enduml