@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ScheduleVisitController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agencyRepository\n:AgencyRepository" as AgencyRepository
participant "agency\n:Agency" as AGC
participant "announcementList\n:AnnouncementList" as LISTCLASS
participant "announcements\n:Announcement" as ANNOUNCE
participant "listAnnouncements\n: List<Announcement>" as AnnounceList


autonumber 4


activate CTRL

      -> CTRL : getAllNonDealAnnouncements()

    autonumber 4.1

    group Get Non Deals List

        CTRL -> RepositorySingleton : getInstance()

        activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getAgencyRepository()

        activate PLAT

            PLAT -> CTRL : agencyRepository

        deactivate PLAT
|||
        CTRL -> AgencyRepository : getAllNonDealAnnouncements()
        activate AgencyRepository

        AgencyRepository -> AnnounceList** : listToDisplay = create()

       loop for all agencies


            AgencyRepository -> AGC : getNonDealAnnouncements()
            activate AGC

            AGC -> LISTCLASS : getNonDeals()
            activate LISTCLASS

            loop for all announcements

                LISTCLASS -> ANNOUNCE : isDeal()
                activate ANNOUNCE

                    ANNOUNCE --> LISTCLASS : true/false
                deactivate ANNOUNCE

            end loop

                LISTCLASS --> AGC : nonDealsList
            deactivate LISTCLASS

                AGC --> AgencyRepository : nonDealsList
            deactivate AGC

            AgencyRepository -> AnnounceList : addAll(nonDealsList)
            activate AnnounceList
            deactivate AnnounceList
|||
       end loop

            AgencyRepository -> LISTCLASS : sortAnnouncementsByMostRecentAcceptanceDate(nonDealsList)
            activate LISTCLASS

                LISTCLASS --> AgencyRepository : nonDealsList
            deactivate LISTCLASS
|||
        end group

            AgencyRepository --> CTRL : nonDealsList
        deactivate AgencyRepository


    autonumber 5
    <-- CTRL  : nonDealsList
deactivate CTRL


@enduml




@enduml