@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US002

autonumber

actor "Agent" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to make sale/rent announcement
    activate System

        System --> Employee : requests data (type of property; area; location; DCC; price; \nphotographs; number of: bedrooms,bathrooms and parking spaces; \navailable equipment; existence of basement; inhabitable loft; sun exposure)
    deactivate System

    Employee -> System : types requested data (type of property; area; location; DCC; price; \nphotographs; number of: bedrooms,bathrooms and parking spaces; \navailable equipment; existence of basement; inhabitable loft; sun exposure)
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirmes data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml