@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "filtersRepository\n:FiltersRepository" as FILTERSREP

autonumber 5
-> CTRL : getFiltersList()

autonumber 5.1

activate CTRL
    group Get Filters List
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getFiltersRepository()
        activate PLAT

        PLAT --> CTRL: filtersRepository
        deactivate PLAT

        CTRL -> FILTERSREP : getFiltersList()
        activate FILTERSREP

        FILTERSREP --> CTRL : filtersList
        deactivate FILTERSREP

    end group

    autonumber 6
    <-- CTRL : filtersList

deactivate CTRL


@enduml