@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Unregistered User" as User
participant ":DisplayPropertiesUI" as UI
participant ":DisplayPropertiesController" as CTRL
participant "filtersRepository\n:FiltersRepository" as FILTERSREP
participant "agencyRepository\n: AgencyRepository" as AGENCYREP
participant "agency\n: Agency" as AGENCY


activate User

    User -> UI : asks to display listed properties
    activate UI

    UI -> CTRL** : create

    UI -> CTRL : getAnnouncements()
    activate CTRL

        ref over CTRL
            Get Announcements List

        end ref

     CTRL --> UI : announcementList
     deactivate CTRL

     UI -> CTRL : getFiltersList()
     activate CTRL

     ref over CTRL
         Get Filters List

     end ref

         CTRL --> UI : filtersList
         deactivate CTRL

    UI --> User : display listed properties by most recent added


    opt business type
        UI --> User : shows types of business and asks to select one
        deactivate UI

        User -> UI : selects data (businessType)
        activate UI

        UI -> CTRL :  getAnnouncements(announcements, businessType)
        activate CTRL

        CTRL -> AGENCYREP : getAnnouncements(announcements, businessType)
        activate AGENCYREP

        AGENCYREP -> AGENCY : getAnnouncementsByBusinessType(announcementList,\n businessType)
        activate AGENCY

        ref over AGENCY
            Get Announcements By Business Type

        end ref

        AGENCY --> AGENCYREP : announcementList
        deactivate AGENCY

        AGENCYREP --> CTRL : announcementList
        deactivate AGENCYREP

        CTRL --> UI : announcementList
        deactivate CTRL

         UI --> User : display all the listed properties, according to the \ncriteria chosen
         |||
    end

    opt property type
        UI --> User : shows types of properties and asks to select one
        deactivate UI

        User -> UI : selects data (propertyType)
        activate UI

    UI -> CTRL :  getAnnouncements(announcements, propertyType)
    activate CTRL

    CTRL -> AGENCYREP : getAnnouncements(announcements, propertyType)
    activate AGENCYREP

    AGENCYREP -> AGENCY : getAnnouncementsByPropertyType(announcementList,\n propertyType)
    activate AGENCY

    ref over AGENCY
        Get Announcements By Property Type

    end ref

        AGENCY --> AGENCYREP : announcementList
        deactivate AGENCY

        AGENCYREP --> CTRL : announcementList
        deactivate AGENCYREP

        CTRL --> UI : announcementList
        deactivate CTRL

        UI --> User : display all the listed properties, according to the \ncriteria chosen
        |||
    end

    alt propertyType != land
    |||
    opt number of bedrooms

        UI --> User : shows options for number of bedrooms and asks to select one
        deactivate UI

        User -> UI : selects data (numberBedrooms)
        activate UI

        UI -> CTRL :  getAnnouncements(announcements, numberBedrooms)
        activate CTRL

        CTRL -> AGENCYREP : getAnnouncements(announcements, numberBedrooms)
        activate AGENCYREP

        AGENCYREP -> AGENCY : getAnnouncementsByNumberBedrooms(announcementList,\n numberBedrooms)
        activate AGENCY

        ref over AGENCY
            Get Announcements By Number of Bedrooms

        end ref

    AGENCY --> AGENCYREP : announcementList
    deactivate AGENCY

    AGENCYREP --> CTRL : announcementList
    deactivate AGENCYREP

    CTRL --> UI : announcementList
    deactivate CTRL

    UI --> User : display all the listed properties, according to the \ncriteria chosen

    |||
    end
    |||
    end

    UI -> UI : sortingList
    activate UI

    UI --> UI
    deactivate UI

    opt price
        UI --> User : shows options for sort properties by price and asks to select one
        deactivate UI

        User -> UI : select data (sortingType)
        activate UI

        UI -> CTRL : sortAnnouncements(price, typeSorting, announcementList)
        activate CTRL

        CTRL -> AGENCYREP : sortAnnouncements(price, typeSorting, announcementList)
        activate AGENCYREP

        AGENCYREP -> AGENCY : sortAnnouncements(price, typeSorting, announcementList)
        activate AGENCY

        ref over AGENCY
            Sort Announcements By Price

        end ref

        AGENCY --> AGENCYREP : announcementList
        deactivate AGENCY

        AGENCYREP --> CTRL : announcementList
        deactivate AGENCYREP

        CTRL --> UI : announcementList
        deactivate CTRL

        UI --> User : display all the listed properties, according to the \ncriteria chosen

    |||
    end

    opt city
        UI --> User : shows options for sort properties by city and asks to select one
        deactivate UI

        User -> UI : select data (sortingType)
        activate UI


        UI -> CTRL : sortAnnouncements(city, typeSorting, announcementList)
        activate CTRL

        CTRL -> AGENCYREP : sortAnnouncements(city, typeSorting, announcementList)
        activate AGENCYREP

        AGENCYREP -> AGENCY : sortAnnouncements(city, typeSorting, announcementList)
        activate AGENCY

        ref over AGENCY
            Sort Announcements By City

        end ref

       AGENCY --> AGENCYREP : announcementList
       deactivate AGENCY

       AGENCYREP --> CTRL : announcementList
       deactivate AGENCYREP

       CTRL --> UI : announcementList
       deactivate CTRL

       UI --> User : display all the listed properties, according to the \ncriteria chosen

    |||
    end


    opt state
        UI --> User :  shows options for sort properties by state and asks to select one
        deactivate UI

        User -> UI : select data (sortingType)
        activate UI

        UI -> CTRL : sortAnnouncements(state, typeSorting, announcementList)
        activate CTRL

        CTRL -> AGENCYREP : sortAnnouncements(state, typeSorting, announcementList)
        activate AGENCYREP

        AGENCYREP -> AGENCY : sortAnnouncements(state, typeSorting, announcementList)
        activate AGENCY

        ref over AGENCY
            Sort Announcements By State

        end ref

        AGENCY --> AGENCYREP : announcementList
        deactivate AGENCY

        AGENCYREP --> CTRL : announcementList
        deactivate AGENCYREP

        CTRL --> UI : announcementList
        deactivate CTRL

        UI --> User : display all the listed properties, according to the \ncriteria chosen
        deactivate UI
    |||
    end

deactivate User

@enduml