@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "agency\n: Agency" as AGENCY

autonumber 50
-> AGENCY : sortAnnouncements(city, typeSorting, announcementList)
activate AGENCY

autonumber 51.1
activate AGENCY
    group Sort Announcements By City

        alt ascending city

            AGENCY -> AGENCY : sortAnnouncementsByAscendingCity(announcementList)
            activate AGENCY

            AGENCY --> AGENCY : announcementList
            deactivate AGENCY

            else descending city

            AGENCY -> AGENCY : sortAnnouncementsByDescendingCity(announcementList)
            activate AGENCY

            AGENCY --> AGENCY : announcementList
            deactivate AGENCY

        |||
        end
    |||
    end

    autonumber 52

    <-- AGENCY : announcementList
deactivate AGENCY


@enduml