@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox
participant "agency\n: Agency" as AGENCY

autonumber 21
-> AGENCY : getAnnouncementsByTypeProperty(announcementList,\n typeProperty)
activate AGENCY

autonumber 21.1
activate AGENCY
    group Get Announcements By Property Type

        loop for each announcement
                AGENCY -> AGENCY : announcementHasTypeProperty(announcementList,\n propertyType)
                activate AGENCY

                AGENCY --> AGENCY: true/false
                deactivate AGENCY

                alt false
                    AGENCY -> AGENCY : removeAnnouncement(announcementList)
                    activate AGENCY

                    AGENCY --> AGENCY: announcementList
                    deactivate AGENCY
                |||
                end
                |||
            end
                |||
    end

    autonumber 22

    <-- AGENCY : announcementList
deactivate AGENCY

@enduml