@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "agency\n: Agency" as AGENCY

autonumber 12
-> AGENCY : getAnnouncementsByBusinessType(announcementList,\n businessType)
activate AGENCY

autonumber 12.1
activate AGENCY
    group Get Announcements By Business Type

        loop for each announcement

                    AGENCY -> AGENCY : announcementHasTypeBusiness(announcementList,\n businessType)
                    activate AGENCY

                    AGENCY --> AGENCY: true/false
                    deactivate AGENCY

                    alt false
                    AGENCY -> AGENCY : removeAnnouncement(announcementList)
                    activate AGENCY

                    AGENCY --> AGENCY: announcementList
                    deactivate AGENCY
                    |||
                   end
                |||
                end
                |||
    end

    autonumber 13

    <-- AGENCY : announcementList
deactivate AGENCY


@enduml