@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "agency\n: Agency" as AGENCY

autonumber 30
-> AGENCY : getAnnouncementsByNumberBedrooms(announcementList,\n numberBedrooms)
activate AGENCY

autonumber 30.1
activate AGENCY
    group Get Announcements By Number of Bedrooms

        loop for each announcement

                AGENCY -> AGENCY : announcementHasNumberBedrooms(announcementList,\n numberBedrooms)
                activate AGENCY

                AGENCY --> AGENCY: true/false
                deactivate AGENCY

                alt false
                AGENCY -> AGENCY : removeAnnouncement(announcementList)
                activate AGENCY

                AGENCY --> AGENCY: announcementList
                deactivate AGENCY
            |||
            end
        |||
        end
    |||
    end

    autonumber 31

    <-- AGENCY : announcementList
deactivate AGENCY


@enduml