@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "agency\n: Agency" as AGENCY

autonumber 39
-> AGENCY : sortAnnouncements(price, typeSorting, announcementList)
activate AGENCY

autonumber 39.1
activate AGENCY
    group Sort Announcements By Price

        alt ascending price

            AGENCY -> AGENCY : sortAnnouncementsByAscendingPrice(announcementList)
            activate AGENCY

            AGENCY --> AGENCY : announcementList
            deactivate AGENCY

            else descending price

            AGENCY -> AGENCY : sortAnnouncementsByDescendingPrice(announcementList)
            activate AGENCY

            AGENCY --> AGENCY : announcementList
            deactivate AGENCY

            |||
        end
    |||
    end

    autonumber 40

    <-- AGENCY : announcementList
deactivate AGENCY


@enduml