@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "agency\n: Agency" as AGENCY

autonumber 59
-> AGENCY : sortAnnouncements(state, typeSorting, announcementList)
activate AGENCY

autonumber 49.1
activate AGENCY
    group Sort Announcements By State

        alt ascending state

            AGENCY -> AGENCY : sortAnnouncementsByAscendingState(announcementList)
            activate AGENCY

            AGENCY --> AGENCY : announcementList
            deactivate AGENCY

            else descending state

            AGENCY -> AGENCY : sortAnnouncementsByDescendingState(announcementList)
            activate AGENCY

            AGENCY --> AGENCY : announcementList
            deactivate AGENCY

        |||
        end
    |||
    end

    autonumber 60

    <-- AGENCY : announcementList
deactivate AGENCY


@enduml