@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US007

autonumber

actor "Unregistered User" as User
participant ":System" as System

activate User

    User -> System : asks to register in the system
    activate System

    System --> User : requests data (name, passportCardNumber, tax number,\n emailAddress, phoneNumber, password)
    deactivate System

    User -> System : types requested data (name, passportCardNumber,taxNumber,\n emailAddress, phoneNumber, password)
    activate System

    System --> User : requests data (location)
    deactivate System

    opt
    User -> System : types requested data (location)
    activate System
    end opt

    System --> User : shows all data and asks for confirmation.
    deactivate System

    User -> System : submits data
    activate System

    System --> User : displays operation success
    deactivate System

@enduml