@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US007

autonumber

actor "Unregistered User" as User
participant ":System" as System

activate User

    User -> System : asks to register in the system
    activate System

        System --> User : requests data
    deactivate System

    User -> System : types requested data

    activate System

        System --> User : sends generated password to email and asks for validation
    deactivate System

    User -> System : validates the typed data
    activate System

        System --> User : displays operation success
    deactivate System

@enduml