@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US007

autonumber

actor "Unregistered User" as User
participant ":System" as System

activate User

    User -> System : asks to register in the system
    activate System

    System --> User : requests data (name, passport's card number,tax number, location,\n email address, telephone number, password)
    deactivate System

    User -> System : types requested data (name, passportCardNumber,taxNumber, location,\n phoneNumber, emailAddress, password)
    activate System

    System --> User : shows all data and asks for confirmation.
    deactivate System

    User -> System : submits data
    activate System

    System --> User : displays operation success
    deactivate System

@enduml