@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Agent" as ADM
participant ":AcceptOrdersUI" as UI
participant ":AcceptOrdersController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agencyRepository\n: AgencyRepository" as AgRep
participant "agency\n: Agency" as AGENCY
participant "announcementList\n: AnnouncementList" as AnnList
participant "announcementMapper\n: AnnouncementMapper" as AnnMAPPER
participant "announcementDto\n: AnnouncementDto" as AnnDTO
participant "requestDto\n: RequestDto" as RequestDTO
participant "orderListDto\n: OrderListDto" as OrderListDTO
participant "orderDto\n: OrderDto" as OrderDTO
participant "employeeDto\n: EmployeeDto" as EmployeeDTO
participant "commissionDto\n: CommissionDto" as CommissionDTO

activate ADM
    ADM -> UI : asks to accept purchase orders
    activate UI

    UI -> CTRL** : create

    UI -> CTRL : getAnnouncementList()
    activate CTRL

    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton

    RepositorySingleton --> CTRL : repositories
    deactivate RepositorySingleton

     CTRL -> PLAT :  getAgencyRepository()
     activate PLAT

     PLAT -> CTRL : agencyRepository
     deactivate PLAT

     CTRL-> AgRep : getAgenciesList()
     activate AgRep

     AgRep --> CTRL : agenciesList
     deactivate AgRep

     CTRL -> AgRep :  getAnnouncementListFromAllAgencies()
     activate AgRep

     loop for each agency
     AgRep -> AGENCY :  getAnnouncementList()
     activate AGENCY

     AGENCY -> AnnList : getList()
     activate AnnList

     AnnList --> AGENCY: announcementList
     deactivate AnnList

     AGENCY --> AgRep: announcementList
     deactivate AGENCY

     AgRep -> AgRep: add(announcementList)
     activate AgRep

     AgRep --> AgRep:
     deactivate AgRep
     |||
     end loop
     AgRep --> CTRL: announcementListAllAgencies
     deactivate AgRep

     CTRL -> AnnList: sortAnnouncementsByOldest(announcementListAllAgencies)
     activate AnnList

     AnnList --> CTRL: sortAnnouncementsByOldest(announcementListAllAgencies)
     deactivate AnnList

     CTRL -> AnnMAPPER : toDTO(announcementListAllAgencies)
     activate AnnMAPPER

         note right AnnMAPPER
         **DÚVIDAS | FALTA FAZER:**
         * Será necessário colocar os mappers do requestDto; orderList....
         * Verificar se é necessário colocar a seta a tracejado de 'volta' (-->)
         end note

     loop for each announcement

     AnnMAPPER -> AnnMAPPER : toDTO(announcement)
     activate AnnMAPPER

     AnnMAPPER -> AnnDTO**: create(announcement)
     deactivate AnnMAPPER
     activate AnnDTO

     AnnDTO -> RequestDTO** : createRequestDTO()

     AnnDTO -> OrderListDTO** : createOrderListDTO()
     activate OrderListDTO

     loop for each order

     OrderListDTO -> OrderDTO** : createOrderDto()

     OrderListDTO -> OrderListDTO : add(orderDto)
     activate OrderListDTO

     OrderListDTO --> OrderListDTO
     deactivate OrderListDTO
     |||
     end loop
     deactivate OrderListDTO

     AnnDTO -> EmployeeDTO** : createEmployeeDTO()

     AnnDTO -> CommissionDTO** : createCommissionDTO()
     deactivate AnnDTO

     AnnMAPPER -> AnnMAPPER: add(announcementDto)
     activate AnnMAPPER

     AnnMAPPER --> AnnMAPPER:
     deactivate AnnMAPPER

     |||
     end loop

     AnnMAPPER --> CTRL : announcementDtoList
     deactivate AnnMAPPER

     CTRL --> UI: announcementDtoList
     deactivate CTRL

    loop for all properties available for purchase

    UI --> ADM : displays properties available for purchase \nand asks to select one
    deactivate UI

    ADM -> UI : selects property
    activate UI

    UI -> CTRL: getPurchaseOrderList(announcementDto)
    activate CTRL

    CTRL -> AnnDTO : orderDtoList = getPurchaseOrderList()
    activate AnnDTO

    deactivate AnnDTO

    CTRL --> UI: orderDtoList
    deactivate CTRL

    loop while acceptanceAnswer != yes \n&& purchaseOrderList != empty

    UI -->  ADM: displays purchase order and asks the acceptance answer
    deactivate UI

    ADM -> UI  : selects acceptance answer
    activate UI

    UI -> CTRL : defineOrderAcceptance(answer,orderDto,announcementDto)
    activate CTRL

        note right CTRL
        O QUE FALTA -->  ** TENHO DÚVIDAS**:
            * Adicionar a accpetanceAnswer às orders do anuncio
            * Fazer o sendNotification()
        end note

    CTRL -> AnnMAPPER: getAnnouncementId(announcementDto)
    activate AnnMAPPER

    AnnMAPPER -> AnnDTO: getAnnouncementId(announcementDto)
    activate AnnDTO

    AnnDTO --> AnnMAPPER: announcementId
    deactivate AnnDTO

    AnnMAPPER --> CTRL: announcementId
    deactivate AnnMAPPER

    CTRL -> AgRep: getAnnouncementById(announcementId)
    activate AgRep

    loop for all agencies
    AgRep -> AGENCY :  getAnnouncementById(announcementId)
    activate AGENCY

    AGENCY -> AnnList : getAnnouncementById(announcementId)
    activate AnnList

    AnnList -> AnnList: anyAnnouncementHasId(announcementId)
    activate AnnList

    AnnList --> AnnList: true/false
    deactivate AnnList

    AnnList --> AGENCY: announcement
    deactivate AnnList

    AGENCY --> AgRep: announcement
    deactivate AGENCY
    end loop

    AgRep --> CTRL : announcement
    deactivate AgRep


    CTRL --> UI : operationSuccess
    deactivate CTRL

    UI --> ADM : displays operation success
    deactivate UI

    end loop
    end loop

    deactivate ADM



@enduml