;@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model


class SystemAdministrator {
}

class Agency {
id
designation
emailAddress
phoneNumber
}

class Employee {
}

class Person{
name
email
passportCardNumber
taxNumber
phoneNumber
}

class Owner{
}

class Customer{
}

class Agent{
}

class StoreManager{
}
class NetworkManager{
}
class Announcement{
acceptanceDate
}

class Visit{
visitDate
startHour
endHour
}
class VisitReport{
 dealProspect
 description
}
class Property{
 area
 distanceCityCenter
}

class Residence{
 numberBedrooms
 numberBathrooms
 parkingSpace
}
class AvailableEquipment{
description
}
class House{
 basement
 inhabitableLoft
 sunExposure
}
class Network{}

class PropertyType{
designation
}
class ResidenceType{
designation
}
class Photograph{
uri
}
class Location{
streetName
city
district
state
zipCode
}
class Business{
price
}
class BusinessType{
designation
}
class Lease{
contractDuration
}
class Commission {
commissionValue
}
class CommissionType {
designation
}
class Request{
requestDate
}
class Order {
orderAmount
acceptanceAnswer
}


SystemAdministrator "0..*" -- Employee: plays as <
SystemAdministrator "1" --- "*" Employee: registers >
SystemAdministrator "1" -- "*" Agency: registers >
Person "1" -- "1" Employee: represented in <
Customer "1"  --- "1" Person: represented in >
Owner "0..*" -- Customer: plays as <
Agent "0..*" ---- "1" Employee: plays as <
StoreManager "0..*" -- "1" Employee: plays as <
NetworkManager "0..*" --- "1" Employee: plays as <
Agent "1" -- "*" Announcement: is published by <
Agent "1" - "*" Visit: schedules >
Customer "1" -- "*" Visit:  requests >
StoreManager "1" -- "1" Agency: manages >
NetworkManager "1" -up- "1" Network: manages >
Agency "1..*" --- "1" Network: is part of >
Request "*" -- "1" Owner: submits <
Visit "1" -- "1" Property: done to >
Residence  ---|>  Property
House --|> Residence
Visit "1" --- "1"  VisitReport: is a description of <
Agent "1" -- "*" VisitReport: registers >
Employee "1" ----- "1" Agency: works in  >
PropertyType "1" -- "1" Property: is a description of >
ResidenceType "1" -- "1" Residence: is a description of >
Property "1" -- "1..*" Photograph: is visualized in >
Property "1"--"1" Location: has address >
Person "1" -- "1" Location: has address >
Agency "1" -- "1" Location: has address >
Residence "1" -left "*"AvailableEquipment: includes >
Announcement "1" -- "1" Commission: is assigned to <
Agency "1" --- "*" Announcement: owns >
Property "1" -up--- "1" Request : < has information about
Request "1" -- "1" Business: is described by >
Business <|-- Lease
BusinessType "1" - "1" Business : describes >
Announcement "1" - "1" Request : is  based on >
Commission "*" - "1" CommissionType : is categorized in >
Agency "1" --- "*" Request : is assigned to >
Agent "1" --- "*" Request : is responsible for >
Agent "1" -- "*" Order : is accepted by <
Order "*" -up- "1" Announcement : is associated to >
Customer "1" -- "*" Order : places a >

@enduml