@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



participant "agency\n: Agency" as AGENCY
participant "requestList\n: RequestList" as ReqList
participant "requestMapper\n: RequestMapper" as ReqMapper
participant "request\n: Request" as REQUEST

autonumber 12
    -> AGENCY: getRequestListByAgentEmail(agentEmail)
    activate AGENCY

group Get Requests List
autonumber 12.1

        AGENCY -> ReqList : getRequestsListByAgentEmail(agentEmail)
        activate ReqList

        loop for each request
         ReqList -> REQUEST : hasAgentWithEmail(agentEmail)
         activate REQUEST

         REQUEST --> ReqList : true/false
         deactivate REQUEST

             alt true
             ReqList -> ReqList : add(request)
             activate ReqList

             ReqList --> ReqList :
             deactivate ReqList
             end

         end

         ReqList -> ReqList : sortRequestByMostRecentAdded(listRequests)
         activate ReqList

         ReqList --> ReqList :
         deactivate ReqList

         ReqList --> AGENCY : requestList
         deactivate ReqList


end group
autonumber 13
     <-- AGENCY: requestList
     deactivate AGENCY

@enduml