@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Agent" as ADM
participant ":ListRequestsUI" as UI
participant ":ListRequestsController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agencyRepository:\nAgencyRepository" as AgencyRepository
participant "agency\n: Agency" as AGENCY
participant "requestList\n: RequestList" as ReqList
participant "requestMapper\n: RequestMapper" as ReqMapper
participant "requestDto\n: RequestDto" as ReqDto
participant "request\n: Request" as REQUEST
participant "comissionTypeMapper\n: CommisionTypeMapper" as ComTypeMapper
participant "comissionType\n: CommissionTypeDto" as ComType

activate ADM

        ADM -> UI : asks to display the requests made to himself

        activate UI

            UI -> CTRL** : create

            UI -> CTRL : getRequestList()
            activate CTRL

                CTRL -> CTRL : getAgentEmail()
                activate CTRL

                ref over CTRL
                    Get Agent Email
                end ref

                 CTRL --> CTRL : agentEmail
                 deactivate CTRL

                CTRL -> PLAT : getAgencyRepository()
                activate PLAT

                    PLAT --> CTRL: agencyRepository
                deactivate PLAT

                CTRL -> AgencyRepository : getAgencyByEmployeeEmail(agentEmail)
                activate AgencyRepository

                loop for each agency
                     AgencyRepository -> AGENCY : anyAgentHasEmail(agentEmail)
                     activate AGENCY

                      AGENCY --> AgencyRepository : true/false
                     deactivate AGENCY
                end

                AgencyRepository --> CTRL : agency
                deactivate AgencyRepository

                CTRL -> AGENCY : getRequestListByAgentEmail(agentEmail)
                activate AGENCY

                AGENCY -> ReqList : getRequestListByAgentEmail(agentEmail)
                activate ReqList

                loop for each request
                 ReqList -> REQUEST : hasAgentWithEmail(agentEmail)
                 activate REQUEST

                 REQUEST --> ReqList : true/false
                 deactivate REQUEST

                     alt true
                     ReqList -> ReqList : add(request)
                     activate ReqList

                     ReqList --> ReqList :
                     deactivate ReqList
                     end

                 end

                 ReqList -> ReqList : sortRequestByMostRecentAdded
                 activate ReqList

                 ReqList --> ReqList :
                 deactivate ReqList

                 ReqList --> AGENCY : requestList
                 deactivate ReqList

                AGENCY --> CTRL : requestList
                deactivate AGENCY

                CTRL -> ReqMapper : toDto(requestList)
                activate ReqMapper

                loop for each request
                ReqMapper -> ReqMapper : toDto(request)
                activate ReqMapper

                ReqMapper -> ReqDto : getPropertyAttributes()
                activate ReqDto

                ReqDto --> ReqMapper : propertyAttributes
                deactivate ReqDto

                ReqMapper -> ReqDto : getRequestID()
                activate ReqDto

                ReqDto --> ReqMapper : requestID
                deactivate ReqDto

                ReqMapper -> ReqDto : create
                activate ReqDto
                deactivate ReqDto

                ReqMapper -> ReqMapper : add()
                activate ReqMapper

                ReqMapper --> ReqMapper :
                deactivate ReqMapper
                end

                ReqMapper --> CTRL : requestListDto
                deactivate ReqMapper
                |||
                deactivate ReqMapper
                |||

                CTRL --> UI : requestListDto
            deactivate CTRL

            UI --> ADM : shows the list of requests
        deactivate UI

    loop for the requests of the agent

    ADM -> UI : selects a request
    activate UI

    UI -> CTRL : getRequestID(requestIdDto)
    activate CTRL

    CTRL -> ReqMapper : requestId =  getRequestByID(requestIdDto)
    activate ReqMapper

    ReqMapper -> ReqDto : getRequestID
    activate ReqDto

    ReqDto --> ReqMapper : requestId
    deactivate ReqDto

    ReqMapper --> CTRL : requestId
    deactivate ReqMapper

    CTRL -> AgencyRepository : getRequestByID(requestId)
    activate AgencyRepository

    loop for all agencies

        AgencyRepository -> AGENCY : getRequestByID(requestId)
        activate AGENCY

            AGENCY -> ReqList : getRequestByID(requestId)

            loop for all requests

                activate ReqList

                ReqList --> REQUEST : hasSameId(id)

                activate REQUEST

                    REQUEST --> ReqList : true/false
                deactivate REQUEST
            end
    end

    ReqList --> AGENCY : request
    deactivate ReqList

    AGENCY --> AgencyRepository : request
    deactivate AGENCY

    AgencyRepository --> CTRL :request
    deactivate AgencyRepository




    CTRL --> UI : request
    deactivate CTRL



    UI --> ADM : shows the request and asks data (option)
    deactivate UI

    ADM -> UI : submits data (option)
    activate UI

    alt option == accept

          UI -> CTRL : getCommissionTypeLis()
          activate CTRL

          CTRL -> CTRL : getCommissionTypeList()
          activate CTRL

            ref over CTRL
            Get Commission Type List
            end ref

            CTRL --> CTRL : commissionTypeList
            deactivate CTRL

                CTRL -> ComTypeMapper : toDto(commissionTypeList)
                activate ComTypeMapper

                ComTypeMapper -> ComTypeMapper : toDto(commissionTypeList)
                activate ComTypeMapper

                ComTypeMapper -> ComType : getCommissionsType()
                activate ComType

                ComType --> ComTypeMapper : commissionsType
                deactivate ComType

                deactivate ComTypeMapper
                |||
                ComTypeMapper --> CTRL : comssionTypeListDto
                deactivate ComTypeMapper


              CTRL --> UI : commissionTypeListDto
              deactivate CTRL

            UI --> ADM : shows types of commission and asks to select one
            deactivate UI

            ADM -> UI : selects type of commission
            activate UI

            UI --> ADM : requests value of commission
            deactivate UI

            ADM -> UI : enters commission value
            activate UI

            UI --> ADM : shows all data and asks to submits
            deactivate UI

            ADM -> UI : submits data
            activate UI

            UI -> CTRL : publishAnnouncement(commissionTypeDesignation, commissionValue, request, email)
            activate CTRL


            CTRL -> AGENCY: getAgentByEmail(email, agency)
            activate AGENCY

            AGENCY --> CTRL : agent
            deactivate AGENCY
            |||

            CTRL -> CTRL : getCommissionTypeByDescription(commissionTypeDesignation)
            activate CTRL
                ref over CTRL
                Get Commission Type
                end ref
            CTRL --> CTRL : commissionType
            deactivate CTRL
             |||

                CTRL -> AGENCY: publishAnnouncement(agent, commissionType commissionValue, request)

                    ref over AGENCY
                        Publish Announcement
                    end ref

                    activate AGENCY

                AGENCY --> CTRL: announcement
                deactivate AGENCY

                CTRL --> UI: announcement
                deactivate CTRL

    else option == decline

            UI --> ADM : asks for justification message
            deactivate UI

            ADM -> UI : submits message
            activate UI

            UI -> CTRL : getOwnerEmail()
            activate CTRL

            CTRL -> AGENCY : getOwnerEmail()
            activate AGENCY

            AGENCY -> REQUEST : getOwnerEmail()
            activate REQUEST

            REQUEST --> AGENCY : ownerEmail
            deactivate REQUEST

            AGENCY --> CTRL : ownerEmail
            deactivate AGENCY

            CTRL --> UI : ownerEmail
            deactivate CTRL

            UI -> CTRL : sendEmail(owner, message)
            activate CTRL

            CTRL -> REQUEST : sendEmail(ownerEmail, message)
            activate REQUEST

            REQUEST --> CTRL : confirmation
            deactivate REQUEST

            CTRL --> UI : confirmation
            deactivate CTRL

    end


    UI --> ADM : shows operation success and shows the list of requests
    deactivate UI


deactivate ADM

end

@enduml