@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ListRequestsController" as CTRL
participant "commissionTypeMapper\n: CommissionTypeMapper" as ComTypeMapper
participant "commissionType\n: CommissionTypeDto" as ComType

autonumber 4
    -> CTRL: toDto(commissionTypeList)
    activate CTRL

group Convert commission type list to DTO

autonumber 4.1
    CTRL -> ComTypeMapper : toDto(commissionTypeList)
    activate ComTypeMapper

'    ComTypeMapper -> ComTypeMapper : toDto(commissionTypeList)
'    activate ComTypeMapper

    ComTypeMapper -> ComType : getCommissionsType()
    activate ComType

    ComType --> ComTypeMapper : commissionsType
    deactivate ComType

'    ComTypeMapper --> ComTypeMapper :
'    deactivate ComTypeMapper

    ComTypeMapper --> CTRL : commissionTypeListDto
    deactivate ComTypeMapper

end group
autonumber 5
     <-- CTRL: commissionTypeListDto
     deactivate CTRL

@enduml