@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US004


class Request {
    reference
    description
    area
    price or rent
    DCC
    renting contract duration
    photographs
}


class Land extends Request{
    \n
}

class House extends Request{
    bedrooms
    bathrooms
    central heating
    air conditioning
    basement
    inhabitable loft
    sun exposure
}

class Apartment extends Request{
    bedrooms
    bathrooms
    central heating
    air conditioning
}

class Agent {
    name
    email
    password
    position
    reference code
    phone
}

class Owner {
    name
    email
    password
    position
    reference code
    phone
}


'class User {
'    name
'    email
'    password
'    reference code
'    phone
'}

Owner "1" -- "*" Request : creates >
Request "1" - "1" Agent : associated to >
Owner "1" -- "1" Agent : delegates >
'Task "*" -- "1" Employee: created by >
'Employee "0..1" -- "1" User: acts as >
@enduml