@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

title Use Case Diagram

left to right direction

    usecase "UC1 - " as UC1
        "Unregistered User" --> UC1
    usecase "UC2 - To publish an announcement" as UC2
        "Agent" --> UC2
    usecase "UC3 - " as UC3
        "System Administrator" --> UC3
     usecase "UC4 - " as UC4
         "Owner" --> UC4

@enduml