@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class User{
name
email
password
}
class Role{
id
description
}
class Customer{
}
class Owner{
}
class Person{
passportCardNumber
taxNumber
phoneNumber
name
emailAdress
}

User "*" -- "*" Role : plays >
Customer -up-|> Person
Owner -left--|> Person
Person -- User : is represented by >


@enduml