@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Client" as Costumer
participant ":OrderRequestUI" as UI
participant ":OrderRequestController" as CTRL
participant "announcementList\n:AnnouncementList" as LISTCLASS


activate Costumer

    Costumer -> UI : asks to initiate an order request for a property
            activate UI

        UI -> CTRL** : create

        UI -> CTRL : getAnnouncementListDto()
            activate CTRL

        CTRL -> CTRL : getAnnouncementList()
        activate CTRL
                ref over CTRL
                    Get Announcements List
                end ref
            CTRL --> CTRL : listToDisplay
        deactivate CTRL
    |||
        CTRL -> CTRL : toDto(listToDisplay)
        activate CTRL
                ref over CTRL
                    Convert Display List to DTO
                end ref
            CTRL --> CTRL : listToDisplayDto
        deactivate CTRL

            CTRL --> UI : listToDisplayDto
        deactivate CTRL

            UI --> Costumer : shows announcements list
        deactivate UI

            opt Selection of criterias

            Costumer -> UI : asks to select filter for list
            activate UI

            UI -> CTRL : getCriteriaList()
            activate CTRL
               CTRL -> CTRL : getCriteriaList()
                activate CTRL
                        ref over CTRL
                            Get Criteria List
                        end ref
                    CTRL --> CTRL : criteriaList
                deactivate CTRL

            CTRL --> UI : criteriaList
            deactivate CTRL

            UI --> Costumer : shows criteria list

            deactivate UI

                loop For each criterion

                    Costumer -> UI : selects criteria
                    activate UI

                    UI -> CTRL : getFilteredList(criteria)

                    activate CTRL

                        CTRL -> LISTCLASS : listToDisplay = sortListByCriteria(criteria)
                        activate LISTCLASS

                            LISTCLASS --> CTRL : listToDisplay
                        deactivate LISTCLASS

                        |||
                            CTRL -> CTRL : toDto(listToDisplay)
                            activate CTRL
                                    ref over CTRL
                                        Convert Display List to DTO
                                    end ref
                                CTRL --> CTRL : listToDisplayDto
                            deactivate CTRL

                                CTRL --> UI : listToDisplayDto
                            deactivate CTRL

                                UI --> Costumer : shows announcements list
                            deactivate UI

                    deactivate CTRL

                    deactivate UI

                end loop
            end opt

    Costumer -> UI : selects an announcement
            activate UI

        UI -> CTRL : toModel(announcementDto)
        activate CTRL
            ref over CTRL
                Convert Announcement DTO
                 to Model
            end ref

            CTRL --> UI : announcement
        deactivate CTRL


    UI --> Costumer : Requests data
    deactivate UI

    loop While orderAmount > amount

        Costumer --> UI : Types requested data (orderAmount)
        activate UI

        UI --> CTRL : orderRequestFromAnnouncement(announcement, orderAmount)
        activate CTRL

        CTRL --> CTRL : orderRequest(orderAmount)

        ref over CTRL
            Place Order Request
        end ref

        CTRL --> CTRL : confirmation
    end loop

    CTRL --> UI : Confirmation
    deactivate CTRL

    UI --> Costumer : Display operation success
    deactivate UI







deactivate Costumer

@enduml