;@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

class Company {
}

class SystemAdministrator {
}

class Agency {
ID
designation
emailAddress
contactNumber
}

class Employee {
}

class Person{
name
citizenCardNumber
taxNumber
emailAddress
contactNumber
}


class Owner{
}

class Customer{
}

class Agent{
}

class StoreManager{
}
class NetworkManager{
}
class Announcement{
typeCommission
amountCommission
}

class Visit{
date
}
class VisitReport{
 dealProspect
 description
}
class Property{
 area
 distanceCityCenter
}

class Residence{
 numberBedrooms
 numberBathrooms
 parkingSpace
}
class AvailableEquipment{
description
}
class House{
 basement
 inhabitableLoft
 sunExposure
}
class Network{}
class Client{
}
class TypeProperty{
designation
}
class TypeResidence{
designation
}
class Photograph{
url
}
class Location{
streetName
city
district
state
zipCode
}
class Price{
amount
}
class Lease{
contractDuration
}


Company "1" --- "1..*" Agency : owns >
Company "1" --- "1" SystemAdministrator : knows >
SystemAdministrator --|> Employee
SystemAdministrator "1" --- "*" Employee: registers >
SystemAdministrator "1" -- "*" Agency: registers >
Person  <|--  Employee
Person <|-- Owner
Customer  --|> Person
Agent  ----|> Employee
StoreManager --|> Employee
NetworkManager ---|> Employee
Agent "1" --- "*" Announcement: publishes >
Agent "1" - "*" Visit: schedules >
Customer "1" -- "*" Visit:  requests >
StoreManager "1" -- "1" Agency: manages >
NetworkManager "1" -up- "1" Network: manages >
Agency "1..*" --- "1" Network: is part of >
Company "1" -- "1" Network: owns >
Announcement "1" -- "1" Property: contains >
Announcement "*" - "1" Owner: requests <
Visit "1" -- "1" Property: done to >
Residence  --|>  Property
House --|> Residence
Visit "1" - "1"  VisitReport: is a description of <
Agent "1" -- "*" VisitReport: registers >
Client "1" - "1..*" Announcement: views >
Employee "1" ----- "1" Agency: works in  >
TypeProperty "1" -- "1" Property: is a description of >
TypeResidence "1" -- "1" Residence: is a description of >
Property "1" -- "1..*" Photograph: contains >
Property "1"--"1" Location: contains >
Property "1" -- "1" Price: contains >
Price <|-- Lease
Person "1" ---- "1" Location: contains >
Agency "1" ---- "1" Location: contains >
Residence "1" -- "*"AvailableEquipment: contains >

@enduml