@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ListRequestsController" as CTRL
participant "requestMapper\n: RequestMapper" as ReqMapper
participant "request\n: Request" as REQUEST
participant "requestListDto\n:List<RequestDto>" as REQLISTDTO
participant "requestDto\n: RequestDto" as ReqDto

autonumber 14
    -> CTRL: toDto(requestList)
    activate CTRL

group Convert request list to DTO

autonumber 14.1
    CTRL -> ReqMapper : toDto(requestList)
    activate ReqMapper

    ReqMapper -> REQLISTDTO** : create()

    loop for each request
    ReqMapper -> ReqMapper : toDto(request)
    activate ReqMapper

    ReqMapper -> REQUEST : getPropertyAttributes()
    activate REQUEST

    REQUEST --> ReqMapper : propertyAttributes
    deactivate REQUEST

    ReqMapper -> REQUEST : getBusinessAttributes()
    activate REQUEST

    REQUEST --> ReqMapper : businessAttributes
    deactivate REQUEST

    ReqMapper -> REQUEST : getRequestDate()
    activate REQUEST

    REQUEST --> ReqMapper : requestDate
    deactivate REQUEST

    ReqMapper -> REQUEST : getRequestID()
    activate REQUEST

    REQUEST --> ReqMapper : requestID
    deactivate REQUEST

    ReqMapper -> ReqDto : create(propertyAttributes, businessAttributes, requestDate, requestID)
    activate ReqDto
    deactivate ReqDto

    ReqMapper --> ReqMapper : requestDto
    deactivate ReqMapper

    ReqMapper -> REQLISTDTO : add(requestDto)
    activate REQLISTDTO
    deactivate REQLISTDTO
    |||
    end

    ReqMapper --> CTRL : requestListDto
    deactivate ReqMapper
    |||

end group
autonumber 15
     <-- CTRL: requestListDto
     deactivate CTRL


@enduml