@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "System Administrator" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a new employee
    activate System

        System --> Employee : requests data (name, the contact \ntelephone number, tax number, location, the address email)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : shows agencies partner list and asks to \n select one
    deactivate System

    Employee -> System : selects an agency
    activate System


    System --> Employee : shows role and asks to select one
        deactivate System

    Employee -> System : selects a role
            activate System


        System --> Employee : shows selected role, agency and requested \n data
    deactivate System

    Employee -> System : submits data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml