@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US018

autonumber

actor "Store Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to analyze property deals.
    activate System

    System --> Employee : shows regression models available \nand asks to select one.
    deactivate System

    Employee -> System : selects regression model.
    activate System

    opt regressionModel == simple linear
        System --> Employee:  shows the parameters available for regression \nmodels and asks to select one.
         deactivate System
        Employee -> System: selects independent variable.
        activate System
    end alt

    System --> Employee : shows the estimated price for each house\nand apartment deal, and the selected \nregression model report.
    deactivate System


@enduml