@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US002

class Agency {
    designation
    location
    localManager
}

class Advertisement {
    comission
}

class Land extends Property{

}

class House extends Property{
    numBedrooms
    numBathrooms
    centralHeating
    airConditioning
    basement
    inhabitableLoft
    sunExposure
}

class Apartment extends Property{
    numBedrooms
    numBathrooms
    centralHeating
    airConditioning
}

class Property{
    typeProperty
    area
    location
    DCC
    price
    photographs
}

class Agent {
    agency
    adress
    CCN
    contact
    email
    name
    taxNumber
}


Agency "1" - "0..*" Agent : has >
Agent "1" -- "*" Advertisement : creates >
Advertisement "1" -- "1" Property : contains a/Represents  >


@enduml