@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US002

class Agency {
    designation
    location
    localManager
}

class Announcement {
    comission
}
class Property{
 area
 location
 DCC
 photograph
}
class Land{
}
abstract class Residence{
 numberBedrooms
 numberBathrooms
 parkingSpace
availableEquipment
}
class Apartment{
}
class House{
 basement
 inhabitableLoft
 sunExposure
}


class Sale{
price
}
class Lease{
price
contractDuration
}


class Agent {
    agency
    adress
    CCN
    contact
    email
    name
    taxNumber
}


Agent "1" - "1" Agency: works for >
Agent "1" -- "*" Announcement: publishes >
Announcement "1"- "1" Sale: is associated to >
Announcement "1" -- "1" Lease: is associated to >
Announcement "1" -- "1" Property: contains >
Land "1" -- "1" Property: is a >
Residence "1" -- "1" Property:  represents a >
Apartment "1" -- "1" Residence: is a >
House "1" -- "1" Residence: is a >

@enduml