@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant "statistic\n:Statistic" as ST
participant "<interface>\n:RegressionModel" as RM



autonumber

  -> ST  : getStatistics(regressionModelType, dealsDataList)
    activate ST

group   Get Statistics


    ST -> RM**: create(dealsDataList)

        note right RM
        RegressionModel implementation will
        depend on the regression model specified
        in regressionModelType instance.
        end note


    ST -> RM : getRegressionReport()
    activate RM

    RM --> ST : report
    deactivate RM

    ST -> RM: getForecastValues()
    activate RM

    RM--> ST: forecastValues
    deactivate RM

end group

    <-- ST : statistic
    deactivate ST

@enduml