@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "agencyRepository\n:AgencyRepository" as AgencyRepository
participant "dealsDataList\n: List<List<Double>>" as AllDataList
participant "agency\n:Agency" as AGC
participant "announcementList\n:AnnouncementList" as AnnounceList


autonumber
-> AgencyRepository : getAgenciesDataList(regressionModelType,variable)
    activate AgencyRepository

group Get all data for analysis
    |||
    AgencyRepository -> AllDataList** : create()

         loop for all agencies
               AgencyRepository -> AGC : getAnnouncementListDealData(regressionModelType,variable)
               activate AGC


               AGC -> AnnounceList : getDealsData(regressionModelType,variable)
               activate AnnounceList
                    ref over AnnounceList
                         Get Data of Announcements
                    end ref

               AnnounceList --> AGC : dataList
               deactivate AnnounceList

               AGC --> AgencyRepository : dataList
               deactivate AGC

               AgencyRepository -> AllDataList : addAll(dataList)
               activate AllDataList
               deactivate AllDataList
          |||
          end loop

end group
        <-- AgencyRepository  : dealsDataList
        deactivate AgencyRepository


@enduml