@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant "statistic\n:Statistic" as ST
participant "regressionModel\n:RegressionModel" as RM



autonumber

  -> ST  : getStatistics(regressionModelType, dealsDataList)
    activate ST

group   Get Statistics


    ST -> RM**: create(dealsDataList)

        note right RM
        RegressionModel implementation will
        depend on the regression model specified
        in regressionModelType instance.
        end note


    ST -> RM : getModelEquation()
    activate RM

    RM --> ST : equation
    deactivate RM

    ST -> RM: getConfidenceIntervals(intercept, slope)
    activate RM

    RM --> ST: intervals
    deactivate RM

    ST -> RM: getHypothesisTests(intercept, slope)
    activate RM

    RM --> ST: hypothesisTests
    deactivate RM

    ST -> RM: getAnovaSignificanceModel()
    activate RM

    RM --> ST: anovaModel
    deactivate RM

    ST -> RM: getForecastValuesForData(dealsDataList)
    activate RM

    RM--> ST: forecastValues
    deactivate RM

end group

    <-- ST : statistic
    deactivate ST

@enduml