@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction


title Class Diagram - US018


class Agency {
    + getAnnouncementListDealData(regressionModelType,variable)
}

class AnnouncementList {
    - List<Announcement>
    + getDealsData(regressionModelType,variable)
}

class Announcement {
 - isDeal()
 - getSaleAmount()
 + validForAnalysis()
 + getDataForRegression(regressionModelType, variable)

}

class Request {
 + getVariablesValue()
 + getVariableValueByDesignation(variable)
 + isSaleResidence()
}

class Residence {
 + getNumberBedrooms()
 + getNumberBathrooms()
 + getParkingSpace()
 + getVariable(variable)
}
class Property {
 + getArea()
 + getDistanceCityCenter()
}

class AgencyRepository {
    - List<Agency> agencies
    + getAgenciesDataList(regressionModelType,variable)
}
class RegressionModelTypeRepository {
-List<RegressionModelType> regressionModelTypes
    + getRegressionModelTypeList()
}

class RegressionModelType {
- String designation
+ RegressionModelType(designation)
 + getRegressionModelTypeDesignation()
}

class RegressionModelTypeMapper {
 + toDto(regressionModelTypeList)
 - toDto(regressionModelType)
 + toModel(regressionModelTypeDto)
}

class RegressionModelTypeDto {
- String designation
+ getRegressionModelTypeDesignation()
}

class Statistic {
- String report
- List<List<Double>> dealsDataList
- List<Double> forecastValues
+ Statistic(regressionModelType,dealsDataList)
 + getReport()
 + getForecastValues()
 + getDealsDataList()
}

class Business
{
    - Double price
}
class BusinessType
{
- String designation
+ BusinessType(designation)
}

class Repositories {
    - Repositories()
    + getInstance() : repositories
    + getAgencyRepository()
    + getRegressionModelTypeRepository()
}

class AnalyzeDealsController {
    + AnalyzeDealsController(organizationRepository, taskCategoryRepository)
    + getRegressionModelTypeList()
    + getStatisticsAndForecastValues(regressionModelTypeDto, variable)
    - getDataForAnalysis(regressionModelType, variable)
    - getRegressionModelStatistics(regressionModelType, dealsDataList)
}


class AnalyzeDealsUI{
}

class SimpleLinear implements RegressionModel {
- long n
- double intercept
- double slope
- double rSquare
- double r
- double xAverage
- double yAverage
- double Sxx
- double Syy
- double Sxy
- double SE
- double SR
- double ST
- double MSE
- double MSR
- double fObs
- double fSnedecor
- long degreeOfFreedom
- double slopeStdErr
- double slopeLower
- double slopeUpper
- double interceptStdErr
- double interceptLower
- double interceptUpper
- List<List<Double>> dealsData
- SimpleRegression regression
+ SimpleLinear(List<List<Double>> data)
- slopeHypothesisTest()
- interceptHypothesisTest()
- getConfidenceIntervals()
}
class Multilinear implements RegressionModel {
- long n
- long k
- double yAverage
- double[] xAverage
- double[] matrixY
- double[][] matrixX
- double[] beta
- double SE
- double SR
- double ST
- double rSquare
- double rSquareAdjusted
- double MQE
- double MQR
- double fObs
- double fSnedecor
- double[] parametersStdErr
- List<List<Double>> dealsData
- OLSMultipleLinearRegression regression
+ Multilinear(List<List<Double>> data)
- calculateAdjustedRSquared()
- getHypothesisTests()
- getConfidenceIntervals()

}
interface RegressionModel {
+ getRegressionReport()
+ getHypothesisTestDecision(double tObs, double tc)
+ tStudent(double alpha, int degreesOfFreedom)
+ fSnedecor(double alpha, int numeratorDegreeOfFreedom, int denominatorDegreeOfFreedom)
+ addData()
+ getForecastValues()
+ calculateVariablesAverage()
+ compareAnovaSigModel()
}



Repositories -> Repositories : instance

AnalyzeDealsUI .> AnalyzeDealsController
AnalyzeDealsUI .--> RegressionModelTypeDto

RegressionModelTypeMapper .> RegressionModelTypeDto
RegressionModelTypeMapper .-> RegressionModelType

AnalyzeDealsController .> Repositories : repositories

Repositories --> "1" AgencyRepository

AnalyzeDealsController ..> AgencyRepository : AgencyRepository
AnalyzeDealsController ..> RegressionModelTypeRepository : RegressionModelTypeRepository
AnalyzeDealsController ..> Statistic
Statistic .--> SimpleLinear
Statistic .---> Multilinear

RegressionModelTypeRepository --> "*" RegressionModelType

AgencyRepository --> "*" Agency

AnnouncementList "1" --> "*" Announcement : announcements
Announcement --> "1" Request
Request  ---> "1" Property
    Request -> "1" Business
    Business "1" <-- "1" BusinessType
Residence --|> Property
Agency "1" --> "*" Announcement
Agency  --> "1" AnnouncementList : announcements

@enduml