@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Store Manager" as ADM
participant ":AnalyzeDealsUI" as UI
participant ":AnalyzeDealsController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "regressionModelTypeRepository\n:RegressionModelTypeRepository" as RMTRep
participant "agencyRepository\n:AgencyRepository" as AgencyRepository
participant "statistic\n:Statistic" as ST
participant "regressionModelTypeMapper\n:RegressionModelTypeMapper" as RMTMapper
participant "regressionModelTypeDto\n:RegressionModelTypeDto" as RMTDto
participant "regressionModelTypeDtoList\n:List<RegressionModelTypeDto>" as RMTDtoList
participant "regressionModelType\n:RegressionModelType" as RMT



activate ADM

    ADM -> UI : asks to analyze property deals.
    activate UI

    UI -> CTRL**: create()

    UI -> CTRL : getRegressionModelTypeList()
    activate CTRL

    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
    deactivate RepositorySingleton

    CTRL -> PLAT : getRegressionModelTypeRepository()
    activate PLAT

        PLAT --> CTRL: RegressionModelTypeRepository
    deactivate PLAT

    CTRL -> RMTRep : getRegressionModelTypeList()
    activate RMTRep

    RMTRep --> CTRL : regressionModelTypeList
    deactivate RMTRep

    CTRL -> RMTMapper: toDto(regressionModelTypeList)
    activate RMTMapper

    RMTMapper -> RMTDtoList** : create()

    loop for each regressionModelType

    RMTMapper -> RMTMapper : toDto(regressionModelType)
    activate RMTMapper

    RMTMapper -> RMT : getRegressionModelTypeDesignation()
    activate RMT

    RMT --> RMTMapper : regressionModelTypeDesignation
    deactivate RMT

    |||
    RMTMapper -> RMTDto** : create(regressionModelTypeDesignation)


    RMTMapper --> RMTMapper: regressionModelTypeDto
    deactivate RMTMapper
    |||
    RMTMapper -> RMTDtoList: add(regressionModelTypeDto)
    activate RMTDtoList
    deactivate RMTDtoList
    end loop

    RMTMapper --> CTRL : regressionModelTypeDtoList
    deactivate RMTMapper

    CTRL --> UI: regressionModelTypeDtoList
    deactivate CTRL


    UI --> ADM : shows regression models available \nand asks to select one.
    deactivate UI

    ADM -> UI : selects regression model.
    activate UI

    alt regressionModelTypeDto == simple linear
        UI --> ADM: shows the variables available for regression \nmodels and asks to select one.
         deactivate UI
        ADM -> UI: selects variable.
        activate UI
        |||
    end alt

    UI -> CTRL : getRegressionModelStatisticsAndForecastValues(regressionModelTypeDto, variable)
    activate CTRL

    CTRL -> RMTMapper : toModel(regressionModelTypeDto)
    activate RMTMapper

    RMTMapper -> RMTDto : getRegressionModelTypeDesignation()
    activate RMTDto

    RMTDto --> RMTMapper : regressionModelTypeDesignation
    deactivate RMTDto

    RMTMapper -> RMT** : create(regressionModelTypeDesignation)

    RMTMapper --> CTRL : regressionModelType
    deactivate RMTMapper


    |||
    CTRL -> CTRL : getDataForAnalysis(regressionModelType,variable)
    activate CTRL

    CTRL -> PLAT : getAgencyRepository()
    activate PLAT

    PLAT --> CTRL : agencyRepository
    deactivate PLAT


    CTRL -> AgencyRepository : getAgenciesDataList(regressionModelType,variable)
    activate AgencyRepository
        ref over AgencyRepository
         Get all data for analysis
        end ref

    AgencyRepository --> CTRL  : dealsDataList
    deactivate AgencyRepository



    CTRL --> CTRL: dealsDataList
    deactivate CTRL

    |||
    CTRL -> CTRL: getRegressionModelStatistics(regressionModelType, dealsDataList)
    activate CTRL



    CTRL -> ST  : getStatistics(regressionModelType, dealsDataList)
    activate ST
            |||
            ref over ST
            Get Statistics
            end ref

    ST --> CTRL: statistics
    deactivate ST

    CTRL --> CTRL: statistics
    deactivate CTRL

    note right CTRL
        VER MELHOR COMO FAZER ESTE GET
        NO FINAL PRETENDE-SE QUE POSSA IR BUSCAR:
            SLOPE
            INTERCEPT
    end note


    CTRL --> UI : regressionModelStatistics
    deactivate CTRL

    UI --> ADM : shows the estimated price for each house\nand apartment deal, and the selected \nregression model report.
    deactivate UI


deactivate ADM

@enduml