@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreatePropertyController" as CTRL
participant ":AuthFacade" as Auth
participant "userSession\n:UserSession" as SESSION

autonumber 34

-> CTRL : getUserEmail()
activate CTRL

    group Get User Identifier
        autonumber 34.1

        CTRL -> Auth : getCurrentUserSession()

        activate Auth

        Auth --> CTRL : userSession
        deactivate Auth

        CTRL -> SESSION : UserEmail = getUserID()

        activate SESSION

        SESSION --> CTRL : UserEmail
        deactivate SESSION
    end group

autonumber 35

<-- CTRL : UserEmail

@enduml