@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "request\n:Request" as REQUEST
participant "property\n:Property" as PROPERTY
participant "location\n:Location" as LOCATION

autonumber 34.2

            -> REQUEST : create(userEmail, agent, propertyType, businessType, price, area,\n contractDuration, availableEquipment, streetName, city, district,\n state, zipCode, basement, inhabitableLoft, parkingSpace, sunExposure,\n numberBedrooms, numberBathrooms, distanceCityCenter, photograph,\n (agency no ???) )
    activate REQUEST

        group Create Property with Location

        autonumber 34.2.1

            REQUEST -> PROPERTY** : createProperty(propertyType, price, area, contractDuration,\n availableEquipment, streetName, city, district, state, zipCode,\n basement, inhabitableLoft, parkingSpace, sunExposure,\n numberBedrooms, numberBathrooms, distanceCityCenter,\n photograph)
             activate PROPERTY

             PROPERTY -> LOCATION** :createLocation(streetName, city, district, state, zipCode)

            PROPERTY -> PROPERTY : addLocation(location)
            activate PROPERTY

                PROPERTY -> PROPERTY : validateLocation(location)
                activate PROPERTY

                PROPERTY --> PROPERTY
                deactivate PROPERTY

            PROPERTY --> PROPERTY
            deactivate PROPERTY

            deactivate PROPERTY

                REQUEST -> REQUEST : addProperty(property)
                activate REQUEST
                      REQUEST -> REQUEST : validateProperty(property)
                      activate REQUEST

                      REQUEST --> REQUEST
                      deactivate REQUEST
                REQUEST --> REQUEST
                deactivate REQUEST
        |||
        end group

autonumber 34.3
<-- REQUEST : property
deactivate REQUEST
@enduml