@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "request\n:Request" as REQUEST
participant "property\n:Property" as PROPERTY
participant "location\n:Location" as LOCATION

autonumber 35

        -> REQUEST: createRequest(agent, agency, ownerEmail, propertyType, businessType, amount, area,\n contractDuration, availableEquipment, streetName, city, district, state, zipCode,\n basement, inhabitableLoft, parkingSpace, sunExposure, numberBedrooms,\n numberBathrooms, distanceCityCenter, photograph)
        activate REQUEST

            group Create Request

                autonumber 35.1

                REQUEST -> PROPERTY** : createProperty(propertyType, area, contractDuration, streetName, city,\n district, state, zipCode, basement, availableEquipment, inhabitableLoft,\n parkingSpace, sunExposure, numberBedrooms, numberBathrooms,\n distanceCityCenter, photograph)

                activate PROPERTY

               PROPERTY -> LOCATION** : createLocation(streetName, city, district, state, zipCode)

               activate LOCATION

               LOCATION -> LOCATION : validateLocation(location)

                   activate LOCATION

                   LOCATION --> LOCATION

                   deactivate LOCATION

               LOCATION --> PROPERTY : location

               deactivate LOCATION

               |||
               PROPERTY -> PROPERTY : validateProperty(property)

                    activate PROPERTY

                    PROPERTY --> PROPERTY

                    deactivate PROPERTY

               PROPERTY --> REQUEST : property

               deactivate PROPERTY

                |||
               REQUEST -> REQUEST : getCurrentDate()
               activate REQUEST

               REQUEST --> REQUEST :
               deactivate REQUEST

            |||
            end group

        autonumber 36

        <-- REQUEST : request
        deactivate REQUEST
@enduml