@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "request\n:Request" as REQUEST
participant "property\n:Property" as PROPERTY
participant "location\n:Location" as LOCATION

autonumber 35

        -> REQUEST: createRequest(agent, agency, ownerEmail, propertyType, businessType, amount, area,\n contractDuration, availableEquipment, streetName, city, district, state, zipCode,\n basement, inhabitableLoft, parkingSpace, sunExposure, numberBedroom,\n numberBathroom, distanceCityCenter, photograph)
        activate REQUEST

            group Create Request

            |||
                alt Property Type = Land

                autonumber 35.1

                REQUEST -> PROPERTY** : createProperty(propertyType, area, streetName, city, district, state,\n zipCode, distanceCityCenter, photograph)

                                activate PROPERTY

                               PROPERTY -> LOCATION** : createLocation(streetName, city, district, state, zipCode)

                               activate LOCATION

                               LOCATION -> LOCATION : validateLocation(location)

                                   activate LOCATION

                                   LOCATION --> LOCATION

                                   deactivate LOCATION

                               LOCATION --> PROPERTY : location

                               deactivate LOCATION

                               |||
                               PROPERTY -> PROPERTY : validateProperty(property)

                                    activate PROPERTY

                                    PROPERTY --> PROPERTY

                                    deactivate PROPERTY

                               PROPERTY --> REQUEST : property

                               deactivate PROPERTY

                                |||
                               REQUEST -> REQUEST : getCurrentDate()
                               activate REQUEST

                               REQUEST --> REQUEST :
                               deactivate REQUEST
                |||
                else Property Type = Apartment

                autonumber 35.1

                REQUEST -> PROPERTY** : createProperty(propertyType, area, streetName, city, district, state,\n zipCode, availableEquipment, parkingSpace, numberBedroom,\n numberBathroom, photograph, distanceCityCenter)

                activate PROPERTY

               PROPERTY -> LOCATION** : createLocation(streetName, city, district, state, zipCode)

               activate LOCATION

               LOCATION -> LOCATION : validateLocation(location)

                   activate LOCATION

                   LOCATION --> LOCATION

                   deactivate LOCATION

               LOCATION --> PROPERTY : location

               deactivate LOCATION

               |||
               PROPERTY -> PROPERTY : validateProperty(property)

                    activate PROPERTY

                    PROPERTY --> PROPERTY

                    deactivate PROPERTY

               PROPERTY --> REQUEST : property

               deactivate PROPERTY

                |||
               REQUEST -> REQUEST : getCurrentDate()
               activate REQUEST

               REQUEST --> REQUEST :
               deactivate REQUEST

            |||
            else Property Type = House

            autonumber 35.1

                REQUEST -> PROPERTY** : createProperty(propertyType, area, streetName, city, district, state,\n zipCode, basement, availableEquipment, inhabitableLoft, parkingSpace,\n sunExposure, numberBedroom, numberBathroom, photograph,\n distanceCityCenter)

                activate PROPERTY

               PROPERTY -> LOCATION** : createLocation(streetName, city, district, state, zipCode)

               activate LOCATION

               LOCATION -> LOCATION : validateLocation(location)

                   activate LOCATION

                   LOCATION --> LOCATION

                   deactivate LOCATION

               LOCATION --> PROPERTY : location

               deactivate LOCATION

               |||
               PROPERTY -> PROPERTY : validateProperty(property)

                    activate PROPERTY

                    PROPERTY --> PROPERTY

                    deactivate PROPERTY

               PROPERTY --> REQUEST : property

               deactivate PROPERTY

                |||
               REQUEST -> REQUEST : getCurrentDate()
               activate REQUEST

               REQUEST --> REQUEST :
               deactivate REQUEST
            |||
            end alt

        |||
        end group

        autonumber 36

        <-- REQUEST : request
        deactivate REQUEST
@enduml