@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Announcement{
id
acceptanceDate
saleDate
}
class Property{
 area
 distanceCityCenter
}
class Residence{
 numberBedrooms
 numberBathrooms
 parkingSpace
}
class House{
 basement
 inhabitableLoft
 sunExposure
}
class PropertyType{
designation
}
class Business{
price
}
class BusinessType{
designation
}
class Request{
id
requestDate
justificationMessage
}
class Agency {
id
designation
emailAddress
phoneNumber
}


Residence  --|>  Property
House --|> Residence
PropertyType "1" -- "1" Property: is a description of >
StoreManager "1" -- "1" Agency: manages >
Property "1" -up- "1" Request : < has information about
Request "1" -- "1" Business: is described by >
BusinessType "1" - "1" Business : describes >
Announcement "1" - "1" Request : is  based on >
Agency "1" -- "*" Announcement: owns >
StoreManager "1" -- "*" Announcement: analyzes >
@enduml