@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Customer{
}

class Property{
 area
 distanceCityCenter
}

class Order {
orderAmount
acceptanceAnswer
}

class Announcement{
acceptanceDate
}

class Request{
requestDate
}


Customer "1" -- "*" Order : places a >
Order "*" -up- "1" Announcement : is associated to >
Announcement "1" - "1" Request : is  based on >
Property "1" -up--- "1" Request : < has information about

@enduml