@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agencyRepository:\nAgencyRepository" as AgencyRepository

autonumber 12
-> CTRL : getAgencyByDescription(taskCategoryDescription)

autonumber 12.1

activate CTRL
    group Get Task Category
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getTaskCategoryRepository()
        activate PLAT

            PLAT -> CTRL : taskCategoryRepository
        deactivate PLAT

        CTRL -> AgencyRepository : getAgencyByDescription(taskCategoryDescription)
        activate AgencyRepository

            AgencyRepository --> CTRL : taskCategory
        deactivate AgencyRepository

    end group

    autonumber 13
    <-- CTRL : taskCategory

deactivate CTRL


@enduml