@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "data\n:Data" as DATA
participant "agency\n:Agency" as AGENCY

autonumber 16
-> DATA: registerEmployee(name, citizen card \nnumber, tax number, address,\n email address, contact number)

autonumber 16.1
activate DATA
    group Register Employee

        DATA -> AGENCY**: register(name, citizen card \nnumber, tax number, address,\n email address, contact number)
        DATA -> DATA: addEmployee (employee)

        activate DATA
            DATA -> DATA: validateEmployee(employee)
            activate DATA
                DATA --> DATA
            deactivate DATA

            DATA --> DATA
        deactivate DATA
    end

    autonumber 17
    <-- DATA : register
deactivate DATA


@enduml