@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US019

autonumber
actor "Network Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to divide set of stores into two subsets.
    activate System

    System --> Employee : shows sublists and difference of the number of properties.
    deactivate System

@enduml