@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US001


class Announcement{
acceptanceDate
}

class Property{
 area
 distanceCityCenter
}

class Residence{
 numberBedrooms
 numberBathrooms
 parkingSpace
}

class AvailableEquipment{
description
}

class House{
 basement
 inhabitableLoft
 sunExposure
}

class TypeProperty{
designation
}
class TypeResidence{
designation
}
class Photograph{
uri
}
class Location{
streetName
city
district
state
zipCode
}
class Business{
amount
}
class TypeBusiness{
designation
}
class Lease{
contractDuration
}

class Request{
requestDate
}


Residence  --|>  Property
House --|> Residence
TypeProperty "1" -- "1" Property: is a description of >
TypeResidence "1" -- "1" Residence: is a description of >
Property "1" -- "1..*" Photograph: contains >
Property "1"--"1" Location: has address >
Residence "1" -left "*"AvailableEquipment: contains >
Property "1" -up- "1" Request : < has information about
Business <|-- Lease
TypeBusiness "1" -- "1" Business : describes >
Announcement "1" -- "1" Request : is  based on >



@enduml