@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterEmployeeController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agencyRepository:\nAgencyRepository" as AgencyRepository

autonumber 12
-> CTRL : getAgencyByDescription(agencyByDescription)

autonumber 12.1

activate CTRL
    group Get Agency
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getAgencyRepository()
        activate PLAT

            PLAT -> CTRL : agencyRepository
        deactivate PLAT

        CTRL -> AgencyRepository : getAgencyByDescription(agencyByDescription)
        activate AgencyRepository

            AgencyRepository --> CTRL : agency
        deactivate AgencyRepository

    end group

    autonumber 13
    <-- CTRL : agency

deactivate CTRL


@enduml