@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "System Administrator" as ADM
participant ":importLegacyInformationUI" as UI
participant ":importLegacyInformationController" as CTRL
participant "person\n:Person" as PERSON
participant "legacySystem\n:LegacySystem" as LS
participant "legacySystemMapper\n:LegacySystemMapper" as LSMapper
participant "legacySystemDto\n:LegacySystemDto" as LSDto

activate ADM

    ADM -> UI : asks to import information from a legacy system
    activate UI

    UI -> CTRL**: create

    UI --> ADM : requests file path
    deactivate UI

    ADM -> UI : types file path
    activate UI

    UI --> ADM : asks to confirm and submit data
    deactivate UI

    ADM -> UI : submits data
    activate UI

    UI -> CTRL: importInfo(filePath)
    activate CTRL


    loop while file has next line

      CTRL -> LS** : importInformation(filepath)
      activate LS

      LS -> LS : readLineInformationFromFile(filepath)
      activate LS

      LS --> LS: legacySystemInformationList
      deactivate LS

     CTRL <-- LS : legacySystemInformationList
      deactivate LS

      CTRL -> LSMapper : toDto(legacySystemInformationList)
      activate LSMapper

      LSMapper -> LSDto** : create(legacySystemInformationList)

      LSMapper --> CTRL : legacySystemDto
      deactivate LSMapper

    |||
    CTRL -> CTRL : registerAgency(legacySystemDto)
    activate CTRL
    ref over CTRL
        Register Agency
    end ref
    CTRL --> CTRL : agency
    deactivate CTRL
    |||

    CTRL -> CTRL : registerAgent(agency)
    activate CTRL
    ref over CTRL
        Register Agent
    end ref
    CTRL --> CTRL : agent
    deactivate CTRL
    |||

    CTRL -> CTRL : registerPerson(legacySystemDto)
    activate CTRL
    ref over CTRL
        Register Owner
    end ref
    CTRL --> CTRL: person
    deactivate CTRL

    CTRL -> PERSON : getEmailAddress()
    activate PERSON

    PERSON --> CTRL : emailAddress
    deactivate PERSON
|||
    CTRL -> CTRL : PublishAnnouncement(legacySystemDto, agency, agent, ownerEmail)
    activate CTRL
    ref over CTRL
        Publish Announcement
    end ref
        CTRL --> CTRL
    deactivate CTRL

|||
     end loop

    CTRL --> UI: operationSuccess
    deactivate CTRL

    UI --> ADM : displays operation success
    deactivate UI

@enduml