@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "System Administrator" as ADM
participant ":importLegacyInformationUI" as UI
participant ":importLegacyInformationController" as CTRL
participant "legacySystem\n:LegacySystem" as LS

'participant ":Repositories" as RepositorySingleton
 'participant "repositories\n:Repositories" as PLAT
 'participant "taskCategoryRepository:\nTaskCategoryRepository" as TaskCategoryRepository
 'participant ":ApplicationSession" as _APP
 'participant "appSession\n:ApplicationSession" as APP
 'participant "currentSession\n:UserSession" as SESSAO
 'participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
 'participant "organization\n:Organization" as ORG'

activate ADM

    ADM -> UI : asks to import information from a legacy system
    activate UI

    UI -> CTRL**: create

    UI --> ADM : requests file path
    deactivate UI

    ADM -> UI : types file path
    activate UI

    UI --> ADM : asks to confirm and submit data
    deactivate UI

    ADM -> UI : submits data
    activate UI

    UI -> CTRL: importInfo(filePath)
    activate CTRL


    loop while file has next line

    |||
    ref over CTRL
    Import Information from file
    end ref
    |||
    ref over CTRL
    Create Agency
    end ref
    |||
    ref over CTRL
        Register Agent
    end ref
    |||
    ref over CTRL
        Register Owner
    end ref
    |||
    ref over CTRL
        Create Request
    end ref
    |||
    ref over CTRL
        Publish Announcement
    end ref
    |||
     end loop

    CTRL --> UI: operationSuccess
    deactivate CTRL

    UI --> ADM : displays operation success
    deactivate UI

@enduml