@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "System Administrator" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a new employee
    activate System

        System --> Employee : requests data
    deactivate System

    Employee -> System : types requested data (name, citizen's card\n number, the contact telephone number, tax\nnumber, the adress, the address email)
    activate System

        System --> Employee : shows agencies partner list and roles and asks \n to select one
    deactivate System

    Employee -> System : selects an agency and a role
    activate System

        System --> Employee : shows selected agency and role
    deactivate System

    Employee -> System : submits data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml