@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US015

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to see all the booking requests made to \nproperties manage by himself
    activate System

    System --> Agent : requests data
    deactivate System

    Agent -> System : selects requested data (begin date, end date)
    'types
    activate System

    System --> Agent : shows sorting algorithm options and asks to select one
'   sorting algorithm
    deactivate System

    Agent -> System : selects data (sorting algorithm)
    activate System

    System --> Agent : display all booking requests according to the \ndates and algorithm chosen
    deactivate System

@enduml