@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class SystemAdministrator {}


class Employee {}

class Role{
Agent
StoreManager
NetworkManager
}

class Agent{
}

class StoreManager{
}
class NetworkManager{
}

class Data{
name
citizenCardNumber
taxNumber
address
emailAddress
contactNumber
}


class Agency {
designation
emailAddress
contactNumber
}



SystemAdministrator -|> Employee
SystemAdministrator "1" -- "*" Employee: registers >
SystemAdministrator "1" -up- "*" Agency: registers >

Employee "1" -- "1" Agency: works in  >
Role "1" -- "1" Employee: knows  >
Data  <|-up-  Employee
Agent  --|> Employee
StoreManager --|> Employee
NetworkManager --|> Employee


@enduml