@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'hide footbox
participant ":ListDealsNetworkController" as CTRL
participant "agencyRepository\n:AgencyRepository" as AgencyRepository
participant ":AnnouncementMapper" as MAPPER
participant "agency\n:Agency" as AGC
participant "announcementList\n:AnnouncementList" as ANNOUNCELIST
participant "announcement\n:Announcement" as ANNOUNCE
participant "commission\n:Commission" as COMMISSION
participant "request\n:Request" as REQUEST
participant "employee\n:Employee" as EMPLOYEE
participant "announcementListDto\n:List<AnnouncementDto>" as LISTDTO
participant "announcementDto\n:AnnouncementDto" as ANCDTO

autonumber 20

    -> CTRL : toDto(listOfAllDeals)

    activate CTRL

group Convert List to DTO

    autonumber 20.1

        CTRL -> AgencyRepository : getAgenciesList()
        activate AgencyRepository

        AgencyRepository -> CTRL : agenciesList
        deactivate AgencyRepository

       CTRL -> MAPPER : toNetworkDto(listOfAllDeals, agenciesList)
        activate MAPPER

        MAPPER -> LISTDTO** : listOfAllDealsDto = create()

        loop for all announcements

        MAPPER -> ANNOUNCELIST : getAnnouncement(idx)
        activate ANNOUNCELIST

            ANNOUNCELIST --> MAPPER : announcement
        deactivate ANNOUNCELIST

        MAPPER -> ANNOUNCE : getSaleDate()
        activate ANNOUNCE

            ANNOUNCE --> MAPPER : saleDate
        deactivate ANNOUNCE

        MAPPER -> ANNOUNCE : getId()
        activate ANNOUNCE

        ANNOUNCE --> MAPPER : announcementId
        deactivate ANNOUNCE

        MAPPER -> ANNOUNCE : getRequestDate()
        activate ANNOUNCE

        ANNOUNCE --> MAPPER : requestDate
        deactivate ANNOUNCE
|||
        MAPPER -> ANNOUNCE : getCommissionInfo()
        activate ANNOUNCE

            ANNOUNCE -> COMMISSION : toString()
            activate COMMISSION

                COMMISSION --> ANNOUNCE : commissionInfo
            deactivate COMMISSION

        ANNOUNCE --> MAPPER : commissionInfo
        deactivate ANNOUNCE
|||

        MAPPER -> ANNOUNCE : getSaleAmount()
        activate ANNOUNCE

            ANNOUNCE --> MAPPER : saleAmount
        deactivate ANNOUNCE

|||
        MAPPER -> ANNOUNCE : getRequestInfo()
        activate ANNOUNCE

            ANNOUNCE -> REQUEST : toString()
            activate REQUEST

                REQUEST --> ANNOUNCE : requestInfo
            deactivate REQUEST

            ANNOUNCE --> MAPPER : requestInfo
        deactivate ANNOUNCE

        MAPPER -> ANNOUNCE : getAgencyId()
        activate ANNOUNCE

            ANNOUNCE -> EMPLOYEE : getAgencyId()
            activate EMPLOYEE

                EMPLOYEE --> ANNOUNCE : agencyId
            deactivate EMPLOYEE

        ANNOUNCE --> MAPPER : agencyId
        deactivate ANNOUNCE
|||
        MAPPER -> MAPPER : getAgencyDescriptionById(agencyId, agenciesList)
        activate MAPPER

        loop for all agencies

         MAPPER -> AGC : hasId()
         activate AGC

         AGC --> MAPPER : true/false
         deactivate AGC

         opt true
              MAPPER -> AGC : getDescription()
             activate AGC

             AGC --> MAPPER : agencyDescription
             deactivate AGC
         end opt

        end loop

            MAPPER --> MAPPER : agencyDescription
        deactivate MAPPER
|||
        MAPPER --> ANCDTO**: create(announcementId, requestInfo, saleDate, saleAmount, requestDate, commissionInfo, agencyDescription, agencyId)

        MAPPER -> LISTDTO : add(announcementDto)
        activate LISTDTO
        deactivate LISTDTO

        end loop

        MAPPER -> CTRL : listOfAllDealsDto
        deactivate MAPPER

end group

    autonumber 21

    <-- CTRL : listOfAllDealsDto

    deactivate CTRL

@enduml