@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":ScheduleVisitController" as CTRL
'participant ":Agency" as AGC
participant ":Agent" as AGT
participant ":Announcement" as ANNOUNCE
participant ":Visit" as VST


        CTRL -> VST** : createVisit(visitDate, visitBeginning, visitEnd)

        activate VST

         VST -> VST : addVisit(visit)
        
             activate VST

                 VST -> VST : validateVisit(visit)
                 activate VST

                 VST --> VST
                 deactivate VST

            VST --> VST
            deactivate VST

         VST --> CTRL : visit
        deactivate VST

          CTRL -> ANNOUNCE : addVisitToList(visit) or (announcement, visit) ????
            activate ANNOUNCE
            |||
                ref over ANNOUNCE
                    Add Visit to Visit List In Announcement
                end ref

@enduml