@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ScheduleVisitController" as CTRL
participant "agencyRepository\n:AgencyRepository" as REP
participant "agency\n:Agency" as AGC
participant "announcementList\n:AnnouncementList" as LISTCLASS

autonumber 4

 -> CTRL : getAnnouncementList()

activate CTRL

    autonumber 4.1

    group Get Announcements List
|||
            CTRL -> REP : listToDisplay = createList()
            activate REP

            REP -> AGC : createList()
            deactivate REP
            activate AGC

            AGC -> LISTCLASS** : create()
             deactivate AGC


           CTRL -> CTRL : getAgencies()
            activate CTRL

            ref over CTRL
                Get Agencies List
            end ref
                CTRL --> CTRL : agenciesList
            deactivate CTRL
|||

            loop for all agencies

                CTRL -> REP : getAnnouncementList()
                activate REP

                REP -> AGC : getAnnouncementList()
                activate AGC

                AGC -> LISTCLASS : getList()
                activate LISTCLASS

                    LISTCLASS --> AGC : announcementList
                deactivate LISTCLASS

                    AGC --> REP : announcementList
                deactivate AGC

                REP --> CTRL : announcementList
                deactivate REP

                CTRL -> LISTCLASS : addAll(announcementList)
                activate LISTCLASS

                LISTCLASS --> CTRL : listToDisplay
                deactivate LISTCLASS
|||
            end loop

            CTRL -> LISTCLASS : sortListByAcceptanceDate(listToDisplay)
            activate LISTCLASS

                LISTCLASS --> CTRL : listToDisplay
            deactivate LISTCLASS
|||
        end group
    autonumber 5
    <-- CTRL  : listToDisplay
deactivate CTRL


@enduml




@enduml