@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ScheduleVisitController" as CTRL
participant "agency\n:Agency" as AGC
participant "announcementList\n:AnnouncementList" as LISTCLASS
participant "announcementList\n:List<Announcement>" as ANCLIST

autonumber 3

 -> CTRL : getAnnouncementListDto()

activate CTRL

    autonumber 3.1

    group Get Announcements List
|||
            CTRL -> LISTCLASS** : listToDisplay = createNewAnnouncementList()
           CTRL -> CTRL : getAgencies()
            activate CTRL

            ref over CTRL
                Get Agencies List
            end ref
                CTRL --> CTRL : agenciesList
            deactivate CTRL
|||

            loop for all agencies

                CTRL -> AGC : getAnnouncementList()
                activate AGC

                AGC -> LISTCLASS : getAnnouncementList()
                activate LISTCLASS

                LISTCLASS -> ANCLIST : getAnnouncementList()
                activate ANCLIST

                    ANCLIST --> LISTCLASS : announcementList
                deactivate ANCLIST

                    LISTCLASS --> AGC : announcementList
                deactivate LISTCLASS

                    AGC --> CTRL : announcementList
                deactivate AGC

                CTRL -> LISTCLASS : listToDisplay.addListContent(announcementList)
                activate LISTCLASS

                LISTCLASS -> LISTCLASS : addAll(announcementList)
                activate LISTCLASS

                LISTCLASS --> LISTCLASS
                deactivate LISTCLASS

                LISTCLASS --> CTRL : listToDisplay
                deactivate LISTCLASS

            end loop

            CTRL -> LISTCLASS : sortListByAcceptanceDate(listToDisplay)
            activate LISTCLASS

                LISTCLASS --> CTRL : listToDisplay
            deactivate LISTCLASS
 |||
                CTRL -> CTRL : toDTO(listToDisplay)
                activate CTRL

                ref over CTRL
                    Convert Display List to DTO
                end ref

                CTRL --> CTRL : listToDisplayDto
                deactivate CTRL
    autonumber 4
    <-- CTRL  : listToDisplayDto
deactivate CTRL


@enduml




@enduml