@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ScheduleVisitController" as CTRL
participant "agency\n:Agency" as AGC
participant "announcementList\n:AnnouncementList" as LISTCLASS

autonumber 4

 -> CTRL : getAnnouncementListDto()

activate CTRL

    autonumber 4.1

    group Get Announcements List DTO
|||
            CTRL -> LISTCLASS** : listToDisplay = createList()
           CTRL -> CTRL : getAgencies()
            activate CTRL

            ref over CTRL
                Get Agencies List
            end ref
                CTRL --> CTRL : agenciesList
            deactivate CTRL
|||

            loop for all agencies

                CTRL -> AGC : getAnnouncementList()
                activate AGC

                AGC -> LISTCLASS : getList()
                activate LISTCLASS

                    LISTCLASS --> AGC : announcementList
                deactivate LISTCLASS

                    AGC --> CTRL : announcementList
                deactivate AGC

                CTRL -> LISTCLASS : addListContent(announcementList)
                activate LISTCLASS

                LISTCLASS -> LISTCLASS : addAll(announcementList)
                activate LISTCLASS

                LISTCLASS --> LISTCLASS
                deactivate LISTCLASS

                LISTCLASS --> CTRL : listToDisplay
                deactivate LISTCLASS

            end loop

            CTRL -> LISTCLASS : sortListByAcceptanceDate(listToDisplay)
            activate LISTCLASS

                LISTCLASS --> CTRL : listToDisplay
            deactivate LISTCLASS
        end group
    autonumber 5
    <-- CTRL  : listToDisplay
deactivate CTRL


@enduml




@enduml