@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ScheduleVisitController" as CTRL
participant "announcement\n:Announcement" as ANNOUNCE
participant "request\n:Request" as REQUEST
participant "property\n:Property" as PROPERTY
participant "visitList\n:List<Visit>" as VLIST
participant "visit\n:Visit" as VST
participant ":Notification" as NTF

autonumber 7

 -> CTRL : sendNotificationMessage(announcement)

activate CTRL

    autonumber 7.1

    group Send Notification Message

'    CTRL -> AgencyRepository : getAgencyByAnnouncement(announcement)
'    activate AgencyRepository
'
'    loop for all agencies
'
'    AgencyRepository -> AGC : hasAnnouncement(announcement)
'    activate AGC
'
'        AGC -> LISTCLASS : hasAnnouncement(announcement)
'        activate LISTCLASS
'
'            LISTCLASS -> ANCLIST : hasAnnouncement(announcement)
'            activate ANCLIST
'
'                ANCLIST --> LISTCLASS : true/false
'            deactivate ANCLIST
'        end loop
'
'            LISTCLASS --> AGC : true
'        deactivate LISTCLASS
'
'        AGC --> AgencyRepository : true
'        deactivate AGC
'
'        AgencyRepository --> CTRL : agency
'    deactivate AgencyRepository
'


        CTRL -> ANNOUNCE : location = getLocation()
        activate ANNOUNCE

            ANNOUNCE ->  REQUEST : getLocation()
            activate REQUEST

                REQUEST -> PROPERTY : getLocation()
                activate PROPERTY

                    PROPERTY --> REQUEST : location
                deactivate PROPERTY

                REQUEST --> ANNOUNCE : location
            deactivate REQUEST

             ANNOUNCE --> CTRL : location
        deactivate ANNOUNCE

        |||
        CTRL -> CTRL : getUserEmail()
        activate CTRL
            ref over CTRL
                Get User Email
            end ref
            CTRL --> CTRL : userEmail
        deactivate CTRL
|||

        CTRL -> ANNOUNCE : sendNotification(location, userEmail)
        activate ANNOUNCE

        ANNOUNCE -> VLIST : sendNotification(location, userEmail)

        loop for all visits

        activate VLIST

            VLIST -> VST : sendNotification(location, userEmail)
        deactivate VLIST

        activate VST

            VST -> NTF** : sendNotification(location, userEmail, visit)
        deactivate VST

        end loop

        ANNOUNCE --> CTRL : confirmation
        deactivate ANNOUNCE
    end group

    autonumber 8

    <-- CTRL  : confirmation
deactivate CTRL

@enduml