@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (SD) - US009

autonumber

actor "<b> Customer </b>" as CTM
participant "<b> :ScheduleVisitUI </b>" as UI
participant "<b> :ScheduleVisitController </b>" as CTRL
participant "announcementList\n:AnnouncementList" as LISTCLASS

activate CTM

    CTM -> UI : asks to schedule a new visit
        activate UI

    UI -> CTRL** : create

    UI -> CTRL : getAnnouncementListDto()
        activate CTRL

    CTRL -> CTRL : getAnnouncementList()
    activate CTRL
            ref over CTRL
                Get Announcements List
            end ref
        CTRL --> CTRL : listToDisplay
    deactivate CTRL
|||
    CTRL -> CTRL : toDTO(listToDisplay)
    activate CTRL
            ref over CTRL
                Convert Display List to DTO
            end ref
        CTRL --> CTRL : listToDisplayDto
    deactivate CTRL

        CTRL --> UI : listToDisplayDto
    deactivate CTRL

        UI --> CTM : shows announcements list
    deactivate UI

    opt Selection of Filters

        loop For each filter
            CTM -> UI : selects filter
            activate UI

            UI -> CTRL : filter

            activate CTRL

                CTRL -> LISTCLASS : listToDisplay = sortListByFilter(filter)
                activate LISTCLASS

                    LISTCLASS --> CTRL : listToDisplay
                deactivate LISTCLASS

                |||
                    CTRL -> CTRL : toDTO(listToDisplay)
                    activate CTRL
                            ref over CTRL
                                Convert Display List to DTO
                            end ref
                        CTRL --> CTRL : listToDisplayDto
                    deactivate CTRL

                        CTRL --> UI : listToDisplayDto
                    deactivate CTRL

                        UI --> CTM : shows announcements list
                    deactivate UI

            deactivate CTRL

            deactivate UI

        end loop
    end opt

    CTM -> UI : selects an announcement
        activate UI

    UI -> CTRL : convertToModel(announcementDto)
    activate CTRL
        ref over CTRL
            Convert Announcement DTO
             to Model
        end ref

        CTRL --> UI : announcement
    deactivate CTRL

    UI --> CTM : requests data
        deactivate UI

    loop While Costumer intends
    CTM -> UI : types requested data (visitDate, startHour, endHour)
        activate UI

        UI -> CTRL : scheduleVisitFromAnnouncement(announcement,\n visitDate, startHour, endHour)

        activate CTRL

        CTRL -> CTRL : scheduleVisit(visitDate, startHour, endHour)
        activate CTRL

        ref over CTRL
            Schedule Visit
        end ref

            CTRL --> CTRL : confirmation
        deactivate CTRL
    |||
    end loop

    CTRL --> UI : confirmation
    deactivate CTRL

    UI --> CTM : displays operation success
        deactivate UI

@enduml