@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (SD) - US009

autonumber

actor "<b> Customer </b>" as CTM
participant "<b> :ScheduleVisitUI </b>" as UI
participant "<b> :ScheduleVisitController </b>" as CTRL

activate CTM

    CTM -> UI : asks to schedule a new visit
        activate UI

    UI -> CTRL** : create

    UI -> CTRL : getAnnouncementListDto()
        activate CTRL
            ref over CTRL
                Get Announcements List DTO
            end ref
    CTRL --> UI : listToDisplayDto
        deactivate CTRL

    UI --> CTM : shows announcements list
        deactivate UI

    CTM -> UI : selects an announcement
        activate UI

    UI -> CTRL : convertToModel(announcementDto)
    activate CTRL
        ref over CTRL
            Convert Announcement DTO
             to Model
        end ref

        CTRL --> UI : announcement
    deactivate CTRL

    UI --> CTM : requests data
        deactivate UI

    loop At least once
    CTM -> UI : types requested data (visitDate, startHour, endHour)
        activate UI

        UI -> CTRL : scheduleVisitRequest(announcement, visitDate,\n startHour, endHour)

        activate CTRL

        CTRL -> CTRL : scheduleVisitRequest(announcement,\n visitDate, startHour, endHour)
        activate CTRL

        ref over CTRL
            Schedule Visit Request
        end ref

        end loop

            CTRL --> CTRL : announcement ?????????
        deactivate CTRL

|||
    CTRL -> CTRL : sendNotificationMessage(announcement)
        activate CTRL

        ref over CTRL
            Send Notification Message
        end ref

    CTRL --> CTRL : confirmation
    deactivate CTRL

    CTRL --> UI : confirmation
    deactivate CTRL

    UI --> CTM : displays operation success
        deactivate UI

@enduml