@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ScheduleVisitController" as CTRL
participant ":AnnouncementMapper" as MAPPER
participant "announcementList\n:AnnouncementList" as LISTCLASS
participant "announcement\n:Announcement" as ANNOUNCE
participant "request\n:Request" as REQUEST
'participant "property\n:Property" as PROPERTY
'participant "residence\n:Residence" as RESIDENCE
'participant "house\n:House" as HOUSE
participant "announcementListDto\n:List<AnnouncementDto>" as LISTDTO
participant "announcementDto\n:AnnouncementDto" as ANCDTO


autonumber 3.16

 -> CTRL : toDTO(listToDisplay)

activate CTRL

    autonumber 3.16.1

    group Convert Display List to DTO

        CTRL -> MAPPER : toDTO(listToDisplay)
        activate MAPPER

        MAPPER -> LISTDTO** : listToDisplayDto = create()

        loop for all announcements

        MAPPER -> LISTCLASS : announcement = get(i)
        activate LISTCLASS
        deactivate LISTCLASS

        MAPPER -> ANNOUNCE : announcementId = getAnnouncementId()
        activate ANNOUNCE

        ANNOUNCE --> MAPPER : announcementId
        deactivate ANNOUNCE
|||
        MAPPER -> ANNOUNCE : requestInfo = getAnnouncementInfoToDisplay()
        activate ANNOUNCE

            ANNOUNCE -> REQUEST : toString()
            activate REQUEST

                REQUEST --> ANNOUNCE : requestInfo
            deactivate REQUEST

            ANNOUNCE --> MAPPER : requestInfo
        deactivate ANNOUNCE
'|||
'        MAPPER -> PROPERTY : photographList = getPhotographList()
'        activate PROPERTY
'
'            PROPERTY --> MAPPER : potographList
'        deactivate PROPERTY
'
'|||
'        alt Property Type = Apartment || Property Type = House
'
'        MAPPER -> RESIDENCE : availableEquipmentList = getAvailableEquipmentList()
'        activate RESIDENCE
'
'            RESIDENCE --> MAPPER : availableEquipmentList
'        deactivate RESIDENCE
'|||
'        alt Property Type = House
'
'        MAPPER -> HOUSE : sunExposure = getSunExposure()
'        activate HOUSE
'
'            HOUSE --> MAPPER : sunExposure
'        deactivate HOUSE
'
'        end alt
'
'        end alt
|||

        MAPPER --> ANCDTO**: create(announcementId, requestInfo)

        MAPPER -> LISTDTO : add(announcementDto)
        activate LISTDTO
        deactivate LISTDTO

        end loop

        MAPPER -> CTRL : listToDisplayDto
        deactivate MAPPER

    end group

    autonumber 3.17
    <-- CTRL  : listToDisplayDto
deactivate CTRL

@enduml