@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ScheduleVisitController" as CTRL
participant ":AnnouncementMapper" as MAPPER
participant "announcementDto\n:AnnouncementDto" as ANCDTO
participant "agencyRepository\n:AgencyRepository" as AgencyRepository
participant "agency\n:Agency" as AGC
participant "announcementList\n:AnnouncementList" as LISTCLASS
participant "announcement\n:Announcement" as ANNOUNCE


autonumber 21

 -> CTRL : convertToModel(announcementDto)

activate CTRL

    autonumber 21.1

    group Convert Announcement DTO to Model

        CTRL -> MAPPER : announcementId = getAnnouncementIdFromDto(announcementDto)
        activate MAPPER

        MAPPER -> ANCDTO : getAnnouncementId()
        activate ANCDTO

            ANCDTO --> MAPPER : announcementId
        deactivate ANCDTO

            MAPPER --> CTRL : announcementId
        deactivate MAPPER

        CTRL -> AgencyRepository : searchAnnouncementById(announcementId)
        activate AgencyRepository

        loop for all agencies

            AgencyRepository -> AGC : getAnnouncementById(announcementId)
            activate AGC

                AGC -> LISTCLASS : getAnnouncementById(announcementId)

                loop for all announcements

                    activate LISTCLASS

                    LISTCLASS --> ANNOUNCE : hasId(announcementId)

                    activate ANNOUNCE

                        ANNOUNCE --> LISTCLASS : true/false
                    deactivate ANNOUNCE

                end loop

        end loop

            LISTCLASS --> AGC : announcement
        deactivate LISTCLASS

            AGC --> AgencyRepository : announcement
        deactivate AGC

            AgencyRepository --> CTRL : announcement
        deactivate AgencyRepository

    end group

    autonumber 22

    <-- CTRL  : announcement
deactivate CTRL

@enduml