@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ScheduleVisitController" as CTRL
participant "announcement\n:Announcement" as ANNOUNCE
participant "visit:Visit" as VST

autonumber 26

    -> CTRL : scheduleVisit(visitDate, startHour, endHour)
    activate CTRL

    autonumber 26.1

    group Schedule Visit

    CTRL -> ANNOUNCE : createVisit(visitDate, startHour, endHour)
    activate ANNOUNCE

    ANNOUNCE -> VST** : create(visitDate, startHour, endHour)

     ANNOUNCE -> ANNOUNCE : addVisit(visit)
     activate ANNOUNCE

     ANNOUNCE -> ANNOUNCE : validateVisit(visit)
     activate ANNOUNCE

        ANNOUNCE --> ANNOUNCE
     deactivate ANNOUNCE

     ANNOUNCE --> ANNOUNCE
     deactivate ANNOUNCE

        ANNOUNCE --> CTRL : visit
    deactivate ANNOUNCE

    end group

    autonumber 27
        <-- CTRL : visit
    deactivate CTRL

@enduml