@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreatePropertyController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "residenceTypeRepository\n:ResidenceTypeRepository" as ResidenceTypeRepository

    -> CTRL : getResidenceTypeByDesignation(residenceTypeDesignation)
    activate CTRL

        group Get Residence Type Object

        CTRL -> RepositorySingleton : getInstances()
        activate RepositorySingleton

        RepositorySingleton --> CTRL : repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getResidenceTypeRepository()

        activate PLAT

        PLAT --> CTRL : residenceTypeRepository
        deactivate PLAT

        CTRL -> ResidenceTypeRepository : getResidenceTypeByDesignation(residenceTypeDesignation)

        activate ResidenceTypeRepository

        ResidenceTypeRepository --> CTRL : residenceType
        deactivate ResidenceTypeRepository

        end group

    <-- CTRL : residenceType
    deactivate CTRL

@enduml