@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreatePropertyController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "residenceTypeRepository\n:ResidenceTypeRepository" as ResidenceTypeRepository


-> CTRL : getResidenceType()

     activate CTRL

     group Get Residence Type List

     CTRL -> RepositorySingleton : getInstance()

     activate RepositorySingleton

     RepositorySingleton --> CTRL : repositories
     deactivate RepositorySingleton

     CTRL -> PLAT : getResidenceTypeRepository()

     activate PLAT

     PLAT --> CTRL : residenceTypeRepository
     deactivate PLAT

     CTRL -> ResidenceTypeRepository : getResidenceType()

     activate ResidenceTypeRepository

     ResidenceTypeRepository --> CTRL : residenceTypeList
     deactivate ResidenceTypeRepository

     end group

     <-- CTRL : residenceTypeList
     deactivate CTRL
@enduml