@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Unregistered user" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to display listed properties
    activate System

        System --> Employee : requests data (name, email, password)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : shows all the listed properties
    deactivate System

    Employee -> System : chooses the criteria for the properties
    activate System

        System --> Employee : display the listed properties, according to the \ncriteria chosen
    deactivate System


@enduml