@startuml
'https://plantuml.com/sequence-diagram

title System Sequence Diagram (SSD) - US001 - Alternative Two

autonumber

actor "Unregistered user" as User
participant ":System" as System

activate User

    User -> System : asks to display listed properties
    activate System

    System --> User : shows all the listed properties and asks to select data
    deactivate System

    alt with criteria
    User -> System : selects data (type of business; type of property; number of rooms)
    activate System

    System --> User : display all the listed properties, according to the \ncriteria chosen and asks to select data
    deactivate System

        opt sort by price or parish

        User -> System : selects data (price; parish)
        deactivate System

        end

    else without criteria

    User -> System : doesn't select any data
    activate System

    System --> User : asks to select data
    deactivate System

        opt sort properties

        User -> System : selects data (sale; rent)
        activate System

        end

    end

    System --> User : display all the listed properties, according to the \ncriteria chosen
    deactivate System


@enduml