@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US001

autonumber

actor "Unregistered user" as User
participant ":System" as System

activate User

'ter em conta a UI que aparece para o cliente ????

    User -> System : asks to display listed properties
    activate System

    System --> User : shows all the listed properties and asks to select data (type of business; \ntype of property; number of bedrooms)
    deactivate System

    alt user selects some criteria
        User -> System : selects data
        activate System

        System --> User : display all the listed properties, according to the \ncriteria chosen and asks to select data (price; city; state)
        deactivate System

        User -> System : selects data (price; city; state)
        deactivate System

    else user doesn't select any criteria

        autonumber 3

        User -> System : doesn't select any data
        activate System

        System --> User : asks to select data (sale; rent)
        deactivate System

        User -> System : selects data (sale; rent)
        activate System

    end

    System --> User : display all the listed properties, according to the \ncriteria chosen
    deactivate System


@enduml